### ISSUE TITLE
DUALSDRAM preferred for releases

### ISSUE THREAD

**Issue by JanGunheD** [MiSTer-devel/PSX_MiSTer#100]
Why are the releases using the single sdram version of PSX? Having SDRAM2 for sound as an option does not hurt, or is there some disadvantage? Without a 2nd SDRAM the feature can be switched off in the GUI of the core.

**Comment by birdybro** [comment]
I can't speak for Robert, but the single SDRAM version is the most compatible version, and the only difference is a humanly imperceptible difference in the sound sampling.

**Comment by makigumo** [comment]
Not to forget that you can't have Dual SDRAM and Analog IO at the same time, IIRC.

**Comment by MilanPolle** [comment]
That is correct, the Analog IO board doesn't function at all with the Dual SDRAM version, including its buttons and (digital plus analog) audio output.

Dual RAM indeed doesn't provide a practical advantage. A minority of users has a Digital IO board and not all of them have a second memory module installed.

**Comment by JanGunheD** [comment]
So the analog features are missing from the Dual SDRAM core version, or do you only mean that a second SDRAM cannot be installed when using the analog board (I know there is no space for it then)? If the latter is the case, then the 2ndSDRAM-Option is just an option that does not hurt anyone. So there is a slight advantage, but no disadvantage.

**Comment by MilanPolle** [comment]
It is an either/or situation. The Analog IO board uses pins that otherwise the second SDRAM module would occupy. So the Dual SDRAM version can't control an Analog IO board, as the pins are in use for the RAM instead. An Analog IO board cannot be used together with a second SDRAM module, only the digital board can.

**Comment by JanGunheD** [comment]
Ah OK, I get it. Unfortunately, that problem will come up again if future cores need a 2nd SDRAM, like maybe the Saturn core. But we will see...
