### ISSUE TITLE
Parappa Demo (Euro Demo 25) - Goes to Try Again at Random

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/PSX_MiSTer#102]
Yes its only a Demo but I thought it best to report this as it differs from Real Hardware.

Euro Demo 25 Parappa The Rapper. The Demo will randomly stop and show the "Try Again" screen.

https://cdn.discordapp.com/attachments/918220604736438272/976075490370658354/Euro_Demo_25_Parappa_issue.MOV

**Comment by Kuba-J** [comment]
the same thing happens in Duckstation

**Comment by davedoc1984** [comment]
Tested in BeetlePSX (Mednafen) and the Demo works as it should do.

**Comment by Fuzzybane** [comment]
completely broken now just displays garbage when gets into game, confirmed by me and Dave

**Comment by RobertPeip** [comment]
works with either "Limit Max CD Speed" or Turbo -> most likely the cpu cannot keep up with CD speed

**Comment by Kuba-J** [comment]
Seems to be fixed, please test again

**Comment by davedoc1984** [comment]
Confirmed Fixed.
