### ISSUE TITLE
Um Jammer Lammy (J)

### ISSUE THREAD

**Issue by TheReflexWonder** [MiSTer-devel/PSX_MiSTer#104]
**Issue**
Roughly half of the sound effects associated with player input are muted during stages; this persists into any stage played afterward

**Reproduce**
Have a Cool rating at the end of Lammy's Stage 7, so that it allows you to freestyle after the song is over

**Workaround**
Don't end Lammy's Stage 7 with a Cool rating

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_20220511

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/PSX_MiSTer/issues/43 - possibly related? Maybe not, but cross-referencing just in case.

**Comment by Kuba-J** [comment]
has anyone tested this game since may ?

**Comment by Kuba-J** [comment]
I can't reproduce it, the game works ok with the cool rating in level 7, freestyle etc.
