### ISSUE TITLE
Diablo (NTSC-U) - Graphical and Audio Glitches

### ISSUE THREAD

**Issue by fignutz** [MiSTer-devel/PSX_MiSTer#105]
**Issue**
Although the game is able to boot up and be played, it is not technically "playable". All in-game fonts, especially fonts with ornate bordering, are jagged and broken/glitched. Additionally, CD audio tends to skip/stutter/loop intermittently whether the game is actively being played or sitting idly with no player input.

**Reproduce**
1. Leave all core settings at the defaults
2. Start the game and wait for into trailers to finish playing. 

**Workaround**
None

**BIOS**
_**Latest obtained via the 'Update_all.sh' script_

**CD Image**
Redump bin/cue

**Core Version**
v220511

**MiSTer Version**
v220517

**Comment by Fuzzybane** [comment]
do you have any options active? if not I can check this one out for you

**Comment by fignutz** [comment]
All core options are set to "default" settings

**Comment by Fuzzybane** [comment]
cool cool, I will test this, a 1 other question about the audio issues, is the bin/cue in its muti-bin format or did you merge it into a single bin?
There is a MiSTer Main issue with single bin/cue and CDDA so to fix that you will need to convert it to CHD

**Comment by Fuzzybane** [comment]
![20220521_195557-screen](https://user-images.githubusercontent.com/102825545/169665600-55b1f7f7-5258-4e80-8cc1-8cfbf65f994b.png)
fonts look fine to me

**Comment by fignutz** [comment]
What about the main screen logo and option texts there?

**Comment by Fuzzybane** [comment]
![20220521_195958-screen](https://user-images.githubusercontent.com/102825545/169665708-3d63d76c-3090-4da5-aa9c-639f85ac9240.png)
look fine too

**Comment by fignutz** [comment]
Hrmm...I'm re-uploading the game to my MiSTer now to capture a screenshot of what I'm getting with my default settings...

**Comment by Fuzzybane** [comment]
ok :)

**Comment by fignutz** [comment]
Sorry @Fuzzybane , this ticket is a mistake. It turns out that there were options enabled for this game (by mistake): "Sync 480i for HDMI" and "Texture Filter On". Once these two settings are forced-off, and the game is reset (not the core), the glitching graphics  and audio go away.
