### ISSUE TITLE
Die Hard Trilogy (NTSC-U) Boot logo Groan

### ISSUE THREAD

**Issue by fignutz** [MiSTer-devel/PSX_MiSTer#106]
**Issue**
When booting into the game with 'Fast Boot' disabled (default), the PS-Logo sound effect 'groan' persists throughout the rest of the game.

**Reproduce**
1. Leave core setting for "Fast Boot" disabled
2. Boot the game, and listen for the SCE/PlayStation Logo sound effect 'groan' (tail end of the logo sound).
3. Listen to how the sound effect groan can still be heard in the background long after the main game has started running.

**Workaround**
Enable 'Fast Boot' option to avoid the sound altogether

**BIOS**
_**Latest obtained via the 'Update_all.sh' script_

**CD Image**
Redump bin/cue

**Core Version**
v220511

**MiSTer Version**
v220517

**Comment by Fuzzybane** [comment]
samn as what I said on your fox hunt issue
