### ISSUE TITLE
Fox Hunt (NTSC-U) Boot logo Groan

### ISSUE THREAD

**Issue by fignutz** [MiSTer-devel/PSX_MiSTer#107]
**Issue**
When booting into the game with 'Fast Boot' disabled (default), the PS-Logo sound effect 'groan' persists throughout the rest of the game.

**Reproduce**
1. Leave core setting for "Fast Boot" disabled
2. Boot the game, and listen for the SCE/PlayStation Logo sound effect 'groan' (tail end of the logo sound).
3. Listen to how the sound effect groan can still be heard in the background long after the main game has started running.

**Workaround**
Enable 'Fast Boot' option to avoid the sound altogether

**BIOS**
_**Latest obtained via the 'Update_all.sh' script_

**CD Image**
Redump bin/cue

**Core Version**
v220511

**MiSTer Version**
v220517

**Comment by Fuzzybane** [comment]
nothing can be done about this at the moment, it happens on early hardware too, Robert thinks he can write a hack to force the SPU to reset when the BIOS ends but we have to wait and see

**Comment by RobertPeip** [comment]
I'll reopen it until the hack/reverb decay is implemented as reminder.

**Comment by RobertPeip** [comment]
Reverb logic is correct but loading of the game was too fast, so that the effect didn't decay enough. It's still not fully decayed but should be about correct now. If anyone has the original disc, feel free to capture a boot process of the game.
