### ISSUE TITLE
Final Fantasy IX (NTSC-U) and Lunar 2 Eternal Blue Complete (NTSC-U) "Start or Continue" selection bug

### ISSUE THREAD

**Issue by fignutz** [MiSTer-devel/PSX_MiSTer#109]
**Issue**
After starting the game, the game's selection cursor rapidly cycles itself at the main menu between "_Start New Game_" and "_Continue..._" options. 

**Reproduce**
1. Leave all core settings at the defaults.
2. Start the game and wait for into trailers to finish playing.
3. The problem exists if you observe the selection cursor behaving as described in the issue area.

**Workaround**
None

**BIOS**
**Latest obtained via the 'Update_all.sh' script

**CD Image**
Redump bin/cue

**Core Version**
v220511

**MiSTer Version**
v220517

**Controller and Interface**
Sony DualShock4 and generic BlueTooth dongle.

**Comment by birdybro** [comment]
Are your settings in miscellaneous set to default? What are your controller settings? (pad1: dualshock?). etc...

**Comment by fignutz** [comment]
I was just about to close this issue. This phenemonon is caused when enabling DS mode ANALOG with these two titles. It also happens with Metal Gear Solid. Setting it to back to DS Digital makes the issue go away.
