### ISSUE TITLE
Cyberwar (Japan) loops intro movie repeatedly

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/PSX_MiSTer#110]
Issue
The intro movie plays on repeat, never gets to the title screen. Also it won't respond to the start button, regardless of digital/analog setting.

Reproduce
Load the game and try to play it.

Workaround
None known.

BIOS
7000

CD Image
Redump bin/cue converted to CHD

Core Version
PSX_20220511

Side notes:
This game doesn't even load up to this point on Mednafen due to "spu status bits issue" in their PSX-TODO notes. The issue does not occur on Duckstation.

**Comment by Fuzzybane** [comment]
I played this game on the core birdy, I didn't convert to CHD though

**Comment by birdybro** [comment]
Resolved. Game is very sensitive to the cd access timing I think. Over wifi with a bad connection to my NAS it didn't work. CD Fast Seek gets past the game loading much much faster. Closing.
