### ISSUE TITLE
Star Ocean The Second Story (USA): E2 error after going into options menu and backing out

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/PSX_MiSTer#111]
Star Ocean: The Second Story (USA) shows an E2 error if you go into the options menu and back out to gameplay. 

Steps:
1. Start the game.
2. Whenever possible, access the menu using Triangle.
3. Go in “Options”.
4. Back out twice (Circle) to return to gameplay.
Result: E2 error appears. 

![AFE90DE9-25ED-4058-9368-534C2C18F99B](https://user-images.githubusercontent.com/86253908/169700435-a28e5180-16c5-4908-ae36-634ed578f351.jpeg)

**Comment by RobertPeip** [comment]
Does the game hang with the E2? Otherwise it's a false positive:
"E2 - CPU exception(only relevant if game shows issues)"

**Comment by AtomicShroom** [comment]
Ah no it doesn’t hang. Seems to play just fine actually! I’ll close it then! Apologies for the noise!
