### ISSUE TITLE
Namco System 10

### ISSUE THREAD

**Issue by johansmolinski** [MiSTer-devel/PSX_MiSTer#112]
Is there any chance this core could be modified to support Namco System 10? I do not know for sure what the differences are between Playstation and System 10, but feature wise they look pretty similar.

**Comment by Fuzzybane** [comment]
I am guessing that this is highly unlikely as the FPGA is already pretty full so if there is anything that needs to be added to run the games then it will not fit

**Comment by RobertPeip** [comment]
It needs >50mhz cpu and >100mhz gpu. This is way beyond what the current design could do on cyclone 5. Sorry
