### ISSUE TITLE
R4: Ridge Racer Type 4 (NTSC-U) - Game freezes during intro/demo loop.

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/PSX_MiSTer#115]
R4: Ridge Racer Type 4 locks up on a black screen with no sound eventually if you leave the intro and demo running.  Resetting the game will remedy this.  Usually happens within a half hour, but sometimes can take longer.  
All core options set to default.

Possible this happens in other versions/regions, but I have not tried yet.

**Comment by Kuba-J** [comment]
I can't reproduce this. I checked the PAL version for an hour and a half and the NTSC version for two hours. Everything works as it should.  

My configuration: last stable core,128sdram, default settings, vsync=0 , MiSTer_unstable_20220525_11ba8b

**Comment by M-Walrus** [comment]
Thanks for checking on your end Kuba.  I was using vsync_adjust 2 when this happened, so I'm testing now to see if that was the root of it.

**Comment by M-Walrus** [comment]
Wiped a new card, ran the tests with vsync adjust 0 and 2 and was not able to reproduce this anymore. most likely an issue with my old SD card.

Closing this issue.
