### ISSUE TITLE
Harry Potter and the Philosophers's Stone (PAL) (GERMAN)

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#116]
**Issue:**
After starting the game you cant select a language to get to the main menue when data cache in enabled. Disabling the feature will fix this problem.
Sometimes the game gets into loops/ hangs audio when you talk to people and the game repeats a sentence over and over until you press square to skip the conversation. Happened 5-6 time in our playthrough.

**Reproduce:**

**Workaround:**
none

**BIOS:**
7002

**CD Image:**
Redump bin/cue

**Core Version:**
last stable version

*reported by LockeBoss on PSX Discord channel

**Comment by ramapcsx2** [comment]
Horrible seek code, that jumps large differences (4500 sectors or more) while trying to keep SPU buffer filled for streaming.
It just barely works on some good condition drives and consoles. A CD-R on a mediocre drive will stutter.
Use this to tune timings so the seeks just barely make it in time for a good benchmark :)

**Comment by ramapcsx2** [comment]
Note for this that jumps <= around 8000 LBA will not engange the sled seek mechanism. Instead they use several large jumps.
Distances above always first engage the sled, then let it settle, then jump for correcting the last bits.
So it's reasonable to set anything above ~8000 LBA to a longer delay.

**Comment by RobertPeip** [comment]
Is there a special situation that can be used to try that? 

I skipped working on it, as 5 times through the whole game seems very hard to even find.

**Comment by ramapcsx2** [comment]
If you've got CD seek logging, it already shows these large jumps in the title screen music.
The actual music stutter happens after New Game > watching the intro > Dumbleman speaks.
His speech and the background music seem to be intended to mix, but the seeking takes too long, and they break up.

**Comment by RobertPeip** [comment]
Cannot reproduce this. No music stutter and no repeating dialogs, but i only played the intro and 10 minutes of the game.

**Comment by Kuba-J** [comment]
It seems , it has been fixed, Philippe from the PSX Discord channel completed the entire game and confirmed that it works ok
