### ISSUE TITLE
Can't load CD after loading EXE

### ISSUE THREAD

**Issue by missionfloyd** [MiSTer-devel/PSX_MiSTer#117]
After loading an EXE (e.g., [padtest](https://github.com/ShendoXT/padtest)), loading a CD and resetting just resets the EXE. The only way to load a CD then is reload the PSX core.

**Comment by RobertPeip** [comment]
Known and will not be fixed. Loading a .exe will patch the BIOS that is only downloaded at core boot.

I will disable CD option when exe was downloaded before and add a comment in readme about it.
