### ISSUE TITLE
Medal of Honor level Vengeance Production doesn't render.

### ISSUE THREAD

**Issue by billconiglio** [MiSTer-devel/PSX_MiSTer#118]
Got to the second to last level in the game and came across the level not rendering. Finished the first objective (find scientist roster) and came across this room with the talk end of a V2 rocket and a black void and can't proceed. Using the US version of the game. Toggling widescreen and data cache doesn't matter. I have two sticks of ram plugged in. I run the update_all script every morning so everything should be up to date. If any other information is needed I'll do my best to provide it. 

Redump CHD game image
MiSTer v220517
PSX v220511
BIOS US 1001

![1](https://user-images.githubusercontent.com/97542663/170558437-dd195792-ba8e-4ace-b102-17acd28e2860.jpg)
![2](https://user-images.githubusercontent.com/97542663/170558444-8c33399f-f020-43ad-a8e6-9e3131dc493a.jpg)
![3](https://user-images.githubusercontent.com/97542663/170558451-edbf8ae3-3aec-405c-9482-8efaded1d826.jpg)

**Comment by Fuzzybane** [comment]
can you make and post a savestate or memory card save, that sounds pretty far into the game for the dev to work his way too whilst fixing other bugs

**Comment by billconiglio** [comment]
I hope this is what's needed. I have my games on an external HDD and the cores on the internal SD. Still getting used to the file structure. Iirc the save sate is in the room in question. The manual save on the memory card would be the start of the level (takes 5 minutes or so to get to the room). 

[Medal of Honor (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8782690/Medal.of.Honor.USA._1.zip)

**Comment by Fuzzybane** [comment]
finished the level on latest test build (20220729) everything rendered fine for me using the memory card posted here, please retest and if you have no issues please close this :)

**Comment by RobertPeip** [comment]
Could be that one of the CD fixes removed this problem.

**Comment by RobertPeip** [comment]
If you still experience a problem, feel free to reopen with more information.
