### ISSUE TITLE
Tom and Jerry PAL

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/PSX_MiSTer#119]
**Issue:** 
E2 and hang when reading memory card

**Reproduce:** 
boot the game. Happens after language selection

**Workaround:** 
remove Memory card in OSD and use savestates

**BIOS** 
7002

**CD Image** 
redump bin/cue

**Core Version / Build date** 
PSX_DualSDRAM20220526.rbf

**Comment by Fuzzybane** [comment]
USA version is fine

**Comment by RobertPeip** [comment]
fixed with new testbuild
