### ISSUE TITLE
Loaded (USA) (En,Fr)

### ISSUE THREAD

**Issue by Count-Duckula-AU** [MiSTer-devel/PSX_MiSTer#122]
**Issue:**
The game freezes while writing a save to memory card
The save file (attached) is successfully written to microSD and works if I reset the system/game and load it

**Reproduce:**
Load the attached savestate
Walk to the right to end the level
Select 'Save' from the game's menu and save the game to memory card 1

**Workaround:**
Use savesatates instead of memory card saves
or
Reset the game and load the save from memory card

**BIOS**
7001

**CD Image**
CHD converted from redump bin/cue

**Core Version / Build date**
PSX_DualSDRAM20220527.rbf
MiSTer_unstable_20220527_14b06d

**Note**
When testing using the official release build of the core and stable main, the game froze while 'looking for memory card in slot 1'

[Loaded (USA) (En,Fr)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8790534/Loaded.USA.En.Fr._1.zip)
[Loaded (USA) (En,Fr).zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8790535/Loaded.USA.En.Fr.zip)
![20220528_131047-screen](https://user-images.githubusercontent.com/35830141/170811385-7a2b0718-ce9a-4d43-b469-81431006f185.png)

**Comment by Kuba-J** [comment]
saving game state works ok in PAL version with TURBO option

**Comment by Kuba-J** [comment]
I checked the PAL and NTSC versions on the PSX , did not encounter any problems with the memory card

**Comment by Fuzzybane** [comment]
this is fixed as of test build 20220826 please close

**Comment by Count-Duckula-AU** [comment]
This issue has been fixed in the 20220826 test build.
Thank you Robert :)
