### ISSUE TITLE
Destruction Derby 2 Demo shows "ED" Error - Registration Demo 01 (SCED-00637)

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/PSX_MiSTer#127]
**Issue:**
When selecting the Destruction Derby 2 Demo on the Registration Demo 01 Disc (SCED-00637), it will show an "ED" error and go no further than that. Other Demos on this disc seem to load and work fine.

**Reproduce:**
Load up Registration Demo 1 and select the Destruction Derby 2 Demo.

**Workaround:**
Play Full Game.

**BIOS:**
1001, 7502

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DualSDRAM20220526

**Comment by RobertPeip** [comment]
Game overwrites stack with OTC DMA that usually should go to end of 8Mbyte area, then uses the written values as address and jumps to it.

8Mbyte mode makes this game work, unclear how it works on a normal psx.

**Comment by davedoc1984** [comment]
Fixed. Thanks Robert :)
