### ISSUE TITLE
Sync issue with direct_video

### ISSUE THREAD

**Issue by atohmdiy** [MiSTer-devel/PSX_MiSTer#129]
Hello,
The image is shaking only with the psx core, all other core are working fine. Clearly a sync problem. I am using a bvm 20f1e, hdmi to vga adapter, direct_video mode in my mister.ini. I try both composite_sync=1 and an external sync combiner without success. User report in Mister forum that this problem only appear in direct video.

I follow the unstable build. At the beginning of the nightly release, direct video wasn't working. Then it was working perfectly for sometimes, and the problem appear with an update. I did some investigation using the nightly build repo, the problem appear the 6 March with the build "179c7f'.

**Comment by Fuzzybane** [comment]
have you tried the latest unstable with the direct video fixes?

**Comment by atohmdiy** [comment]
Yes it's corrected with the latest unstable. Thank you

**Comment by Fuzzybane** [comment]
no worries, can you close this issue please?
