### ISSUE TITLE
Reel Fishing - Must use Fastboot

### ISSUE THREAD

**Issue by Hackmodford** [MiSTer-devel/PSX_MiSTer#131]
I am unable to boot Reel Fishing unless I use the fastboot option.

**Comment by RobertPeip** [comment]
fixed

**Comment by Hackmodford** [comment]
@RobertPeip What fixed it? Is there a specific PR?

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/PSX_MiSTer/commit/9b40b772da95b49d580337c24fdae8cca8d5cce1

**Comment by RobertPeip** [comment]
You can use unstable nightly to test yourself if you want:
https://github.com/MiSTer-unstable-nightlies/PSX_MiSTer/releases/download/unstable-builds/PSX_unstable_20220627_15ed1e.rbf

**Comment by luke86** [comment]
Everything working now with the newest unstable with and without fastboot active.

Tested the following games at least letting the boot to the title menu.

Format: CHD
Reel fishing USA
Reel fishing PAL
Fish eyes Japan (Japanese version of reel fishing)

Also tested reel fishing 2 in these variants just to make sure people can go fishing.
