### ISSUE TITLE
Akuji the Heartless (NTSC-U)

### ISSUE THREAD

**Issue by mailcty** [MiSTer-devel/PSX_MiSTer#133]
Issue:
Missing fog & draw distance/clipping issues similar to the Gex 3D games

Reproduce:
Start a new game, or idle to let it run the attract mode

Workaround:
N/A

BIOS:
SCPH-101

CD Image:
Redump CHD

Core Version:
PSX_20220511

![My Great Capture Screenshot 2022-06-12 01-53-23_cropped](https://user-images.githubusercontent.com/107345737/173225686-28ec2a57-55c0-41c9-bc4b-1a1456c40cc1.png)

**Comment by RobertPeip** [comment]
fixed
