### ISSUE TITLE
controller not recognized

### ISSUE THREAD

**Issue by volkania77** [MiSTer-devel/PSX_MiSTer#135]
Hello everyone
on the Ape Escape chd PAL euro FR game there is no more support for controllers whatsoever

MiSTer  v220605
PSX_20220612.rbf
Bios 7003

thank you

**Comment by Fuzzybane** [comment]
you have it set to DualShock right?

**Comment by volkania77** [comment]
fully functional with my sixaxis dualshock3
and my 8BitDo Pro2

**Comment by volkania77** [comment]
salut

I'm the one who's a problem

Or it's found in others

c'est moi qui est un problème 
ou cela ce retrouve chez d'autre

**Comment by Fuzzybane** [comment]
I can try and acquire a PAL version, it might have something to do with your BIOS though
before I do can you try the 3 BIOS method instead of a random multi region BIOS?

**Comment by Kuba-J** [comment]
Ape Escape PAL (ENG) DualShock 4 + 8bitdo adapter - everything works fine

**Comment by volkania77** [comment]
j'ai un bios par dossier
Euro/US/Jap

I have one bios per file

Euro/US/Jap

**Comment by Fuzzybane** [comment]
1 bios per folder works sure, but it is not the recommended setup anymore
USA boot.rom
JP boot1.rom
EU boot2.rom
all go in games/PSX
set System Type to Auto

**Comment by Kuba-J** [comment]
i will try FR version soon

**Comment by volkania77** [comment]
Ok, I'm going to change my configuration

Do a test and I would give the result

**Comment by volkania77** [comment]
I just changed the configuration as an advisor

But still doesn’t work

I tested in .chd and .bin

It’s strange, it’s the only game that has this problem

**Comment by Kuba-J** [comment]
i tested FR version, works perfectly fine ( DS4 )

**Comment by volkania77** [comment]
I’m going to take on another source to test thanks for the FR test

**Comment by wwark** [comment]
Is DS Mode is importante to activate for this game in FR ?

**Comment by wwark** [comment]
is other games required DS Mode activated like Ape Escape ?

**Comment by wwark** [comment]
the issue could be link the SBI file if not correctly set ?
