### ISSUE TITLE
Aquanaut no Kyuujitsu 2 (NTSC-J)

### ISSUE THREAD

**Issue by mailcty** [MiSTer-devel/PSX_MiSTer#136]
Issue:
Minor visual issues with draw distance effects? (e.g. "shadows" below aquatic life and vertical blurring [that doesn't appear elsewhere](https://www.youtube.com/watch?v=PIMzYOt3cZs))

Reproduce:
Start a new game, or idle to let it run the Demonstration Mode

Workaround:
N/A

BIOS:
SCPH-101

CD Image:
Redump CHD

Core Version:
PSX_20220511

![My Great Capture Screenshot 2022-06-12 18-11-02](https://user-images.githubusercontent.com/107345737/173263865-b815dc7e-0c9b-4932-b85f-f9133b2dc635.png)
![My Great Capture Screenshot 2022-06-12 18-14-16](https://user-images.githubusercontent.com/107345737/173263866-73dea020-b260-42f4-be33-cc47269fe97c.png)

**Comment by RobertPeip** [comment]
fixed
