### ISSUE TITLE
Hard Boiled (Europe)

### ISSUE THREAD

**Issue by 230-v** [MiSTer-devel/PSX_MiSTer#137]
Issue:
Hard Boiled (Europe) hangs at the first FMV, although sound continues to play underneath. 

Reproduce:
Start a new game, FMV will start without player input and freeze almost immediately.

Workaround:
Once when I left the game running in the background it eventually got to the menu to the menu, but it took a long time and I've not been able to reproduce.

BIOS:
7502

CD Image:
Redump BIN/CUE and CHD

Core Version:
PSX_20220511 and PSX_20220612

**Comment by fjmartinez2k** [comment]
I had a long playthrough at this game with nightly build PSX_unstable_20220620_158530.rbf

can you test again with this build?

**Comment by 230-v** [comment]
I have tested again with the build you posted and found it still didn't work. I then changed from vscale_mode=4 to 0 in my ini file and it started working. Modes 4 and 5 cause the game to hang at the FMV but mode 0 gets through. 

Could you test this as well to confirm?

**Comment by fjmartinez2k** [comment]
It's working for me with those settings too, but I don't know if they're actually doing anything, as I'm playing on CRT and the picture looks the same regardless of the vscale_mode I set.

Anyways, setting it to 0 looks like you found yourself a workaround.

Nice game btw, didn't know about it

**Comment by 230-v** [comment]
Thanks for testing, I just tried the game again and it hung even with the above changes, so maybe it'just makes it more likely to get past rather than completely fixing it.

Game's good, well worth a go.

**Comment by RobertPeip** [comment]
works fine for me

**Comment by RobertPeip** [comment]
Please retest with latest mister main, should be fine now

**Comment by 230-v** [comment]
I can confirm that with the latest mister main/psx core the FMV freezing no longer occurs when using vscale_mode 4/5. Tested all versions of the game (Europe/France/Germany/Japan) as well as bin/cue and chd.
