### ISSUE TITLE
Eggs of Steel (NTSC-U)

### ISSUE THREAD

**Issue by mailcty** [MiSTer-devel/PSX_MiSTer#139]
Issue:
Intermittent 2D glitching that affects all moving sprites, in addition to a small flashing banner at the top right

Reproduce:
Load or start a new game/idle to let it run the demo mode

Workaround:
N/A

BIOS:
SCPH-101

CD Images:
Redump CHD & BIN/CUE

Core Version:
PSX_20220511

![My Great Capture Screenshot 2022-06-15 20-25-56](https://user-images.githubusercontent.com/107345737/173986367-409be6ec-7b0c-49be-b714-2e8d590c7ef6.png)
![My Great Capture Screenshot 2022-06-15 20-28-33](https://user-images.githubusercontent.com/107345737/173986372-0bbeeefb-d6cb-4340-802d-a4a8a3d940bd.png)
![My Great Capture Screenshot 2022-06-15 20-30-52](https://user-images.githubusercontent.com/107345737/173986378-fec13c0d-b1d8-4124-81c4-a7844d451aff.png)

**Comment by RobertPeip** [comment]
Sprite glitches are fixed.

"Flashing banner" in upper right edge is normal for this game, it's the color lookup table.
Would usually be hidden in overscan on CRT.
You can use vcrop to 224 pixels to hide it.
