### ISSUE TITLE
Disneys Hercules Action-Spiel (Germany)

### ISSUE THREAD

**Issue by graschbaten** [MiSTer-devel/PSX_MiSTer#140]
Hang in the checking MemoryCard Screen. With and without a inserted MermoryCard.
So the Game is booting but not playable

**Comment by Kuba-J** [comment]
I checked the German version and it works ok, I can't reproduce your problem

![IMG_20220619_021810](https://user-images.githubusercontent.com/95412885/174460927-f0e40ee6-c0c0-4ea9-9588-ce0dc6f57bf2.jpg)

**Comment by graschbaten** [comment]
thx, but really obscure. i got the verified redump version. so i need to check all my settings.

**Comment by graschbaten** [comment]
I try it today once more and it worked! I don't know why but everything is fine
