### ISSUE TITLE
International Superstar Soccer Pro (PAL)

### ISSUE THREAD

**Issue by SatanicNemesis** [MiSTer-devel/PSX_MiSTer#144]
Issue:
The commentators cut off and loop part audio from time to time.

Reproduce:
just play any exhibition game 

Workaround:
Turn the commentary volume to zero

BIOS:

CD Image:
Redump bin/cue

Core Version: 
22.06.18

**Comment by Kuba-J** [comment]
this is not a bug, it is exactly the same on the real PlayStation.
