### ISSUE TITLE
Street Fighter EX Plus Alpha (USA)

### ISSUE THREAD

**Issue by javier-rodas** [MiSTer-devel/PSX_MiSTer#145]
**Issue:**
The game works well and reproduces all the intro and ingame demo, but it doesn't allow to play.

**Reproduce:**
The game reboots after you press START on any option of the main menu.

**Workaround:**
N/A

**BIOS:**
MD5 (boot.rom, US BIOS == SCPH7001) = 1e68c231d0896b7eadcad1d7d8e76129
MD5 (boot1.rom, JP BIOS == SCPH7000) = 8e4c14f567745eff2f0408c8129f72a6
MD5 (boot2.rom, EU BIOS == SCPH7002) = b9d9a0286c33dc6b7237bb13cd46fdee

**CD Image:**
MD5 (Street Fighter EX Plus Alpha (USA).chd) = d6b3722a186dcb2577873962aa9efd88

**Core Version:**
PSX_20220618.rbf

**Comment by javier-rodas** [comment]
Yes, same behavior with default settings and with cache enabled.

**Comment by Fuzzybane** [comment]
Press X on menu options

**Comment by Kuba-J** [comment]
Yes , Fuzz is right here you have to press X, it even says at the bottom that START is to exit the menu

![obraz](https://user-images.githubusercontent.com/95412885/174762016-4184b292-735e-46a9-9c7c-ae43877ab927.png)

**Comment by javier-rodas** [comment]
OH! I completely screwed up. I didn't see that message at the bottom of the screen. The game works without any issue. Thanks guys @Kuba-J @Fuzzybane
