### ISSUE TITLE
Ape Escape (NTSC-U)

### ISSUE THREAD

**Issue by mailcty** [MiSTer-devel/PSX_MiSTer#146]
Issue:
Minor visual issue involving flashing bars above a letterboxed cutscene

Reproduce:
Load this savestate - [Ape Escape (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8964603/Ape.Escape.USA._1.zip)

Workaround:
N/A

BIOS:
SCPH-101

CD Images:
Redump CHD & ImgBurn bin/cue of original disc converted to CHD

Core Version:
PSX_unstable_20220622_19bfc7

![My Great Capture Screenshot 2022-06-22 22-56-10](https://user-images.githubusercontent.com/107345737/175229817-be3b2aec-58ab-45fe-aa1c-4d19918b5f14.png)

**Comment by RobertPeip** [comment]
fixed
