### ISSUE TITLE
Street fighter collection 2 street fighter 2 hyper fighting game freezes in match

### ISSUE THREAD

**Issue by Arcade53** [MiSTer-devel/PSX_MiSTer#148]
I had PSx error E20 on street fighter collection.plus at the I can’t put my name it starts the game over again

**Comment by Fuzzybane** [comment]
which region?

**Comment by Arcade53** [comment]
USA I think

**Comment by Fuzzybane** [comment]
do you mean EX Plus?

**Comment by Arcade53** [comment]
No street fighter collection 2

**Comment by Fuzzybane** [comment]
I played World Warrior got to the game over screen and entered name just fine, no E2 error

**Comment by Fuzzybane** [comment]
which game did you pick from the game select screen on that collection?

**Comment by Fuzzybane** [comment]
thank you, let me try that one too, by the way which version of the core are you using? I am using the latest test build

**Comment by Arcade53** [comment]
I don’t know just updated all today

**Comment by Arcade53** [comment]
It is happened when I started a match it froze then E20 come out.and the other issue is when I finish the I can’t put my name in just starts over the game again

**Comment by Fuzzybane** [comment]
got to 3rd fight, entered my name all was fine

**Comment by Fuzzybane** [comment]
and if you ran update all today then I am guessing you are using the latest public build from the 18th, if you are in the discord get the latest one from either test builds if you use HDMI or from unstable nightlies if you use the Analog IO board for either CRT or Audio

**Comment by Fuzzybane** [comment]
also is your cd image a verified redump cd image?

**Comment by Arcade53** [comment]
I think it was a chd

**Comment by Fuzzybane** [comment]
and also you need to get a high score to enter your name which you should get just for finishing the first fight

**Comment by Fuzzybane** [comment]
was the chd made from a redump image?

**Comment by Arcade53** [comment]
The problem is at the end of the game

**Comment by Arcade53** [comment]
I don’t about redump? What is that

**Comment by Fuzzybane** [comment]
redump is a group that make perfect 1:1 rips of games

**Comment by Fuzzybane** [comment]
and by end of the game you mean after beating Bison?

**Comment by Arcade53** [comment]
Where do I get good roms from then

**Comment by Arcade53** [comment]
Yes bison

**Comment by Fuzzybane** [comment]
> Where do I get good roms from then

I can't answer that here

**Comment by Fuzzybane** [comment]
> Yes bison

ok that might take me a while to do, I am very much a casual fighting game player

**Comment by Arcade53** [comment]
Ok no problem let know if you had the some problem when you finished the game

**Comment by Fuzzybane** [comment]
> Ok no problem let know if you had the some problem when you finished the game

ok I will see what I can do :)

**Comment by Arcade53** [comment]
Amazing have PSX on mister

**Comment by Fuzzybane** [comment]
I give up, I have lost my talent at this game and I can't set it to 1 round to fly through it, I must have contiinued like 10 times on the mirror fight

**Comment by Arcade53** [comment]
I will send a video of it

**Comment by Arcade53** [comment]
Tomorrow

**Comment by Fuzzybane** [comment]
ok :)

**Comment by birdybro** [comment]
> I give up, I have lost my talent at this game and I can't set it to 1 round to fly through it, I must have contiinued like 10 times on the mirror fight

Cheats?

**Comment by Fuzzybane** [comment]
I could do birdy but I am not supposed to be testing with cheats enabled bro

**Comment by birdybro** [comment]
You need to enable the "testing with cheats enabled" cheat.

**Comment by Fuzzybane** [comment]
ok so I used the cheat that allowd me to continue on after 1 round and the game did hang after the Bison fight, I didn't get the E2 error code, the cheat also made it that even if I lost in moved on lol, lost the round to Bison and game froze so I am gonna assume that this is a bug.  @Arcade53 can you rename this bug report to the title of the game please instead of PSX Error

**Comment by Arcade53** [comment]
Yes that is the bug

**Comment by RobertPeip** [comment]
Hopefully you made a savestate before short time before the freeze :)

**Comment by Fuzzybane** [comment]
@RobertPeip now I have confirmed the issue I can cheat my way back there and make a save state :)

**Comment by Arcade53** [comment]
I did not .but I can’t even save my name when the game ends

**Comment by Arcade53** [comment]
Hopefully this issue will get fixed

**Comment by Fuzzybane** [comment]
ohhh I got a random E2 loading to the car bonus round that time

**Comment by Fuzzybane** [comment]
I guess I am gonna have to save state a lot

**Comment by Fuzzybane** [comment]
ok this time I finished the game and it didn't freeze and my save state shows me the ending, sorry Robert it is too random

**Comment by Fuzzybane** [comment]
and @Arcade53 don't worry about name entry, doesn't have a memory card option in game to save your high score anyway

**Comment by Fuzzybane** [comment]
[Street Fighter Collection 2 (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8984914/Street.Fighter.Collection.2.USA._1.zip)
if you wanna see Ryu's ending and enter your name anyway

**Comment by Arcade53** [comment]
![20220625_222302](https://user-images.githubusercontent.com/108152078/175789575-c9a9b35f-2d91-411d-b7db-bd18cd460fe6.jpg)
it has gotten stuck between matches

**Comment by Fuzzybane** [comment]
yeah this randomly happened to me once today

**Comment by Arcade53** [comment]
why does it happen ?

**Comment by Arcade53** [comment]
i am sure you will look in to it

**Comment by Fuzzybane** [comment]
idk, I got a save state with a hang so hopefully Robert can look at it soon and work it out

**Comment by Arcade53** [comment]
thanks

**Comment by Arcade53** [comment]
it is a new core so it is understandable

**Comment by Fuzzybane** [comment]
no worries, I am not a developer, I am just a tester :)

**Comment by Arcade53** [comment]
nice

**Comment by Fuzzybane** [comment]
I got a author tag because I added a single line to the readme.md

**Comment by Arcade53** [comment]
Any news on this ?

**Comment by birdybro** [comment]
It's labeled Priority-2 as opposed to Priority-1. It's only been a few days.

**Comment by Arcade53** [comment]
Ok

**Comment by Arcade53** [comment]
I am not sure if this happens on street fighter 2 world warrior and champion edition ?

**Comment by RobertPeip** [comment]
Thanks a lot for testing it so long to be sure!

**Comment by Arcade53** [comment]
I will test the game again this week.thanks for the help.and for the amazing core that is ps1

**Comment by Arcade53** [comment]
I use update all will that update be there ?

**Comment by Kuba-J** [comment]
no , this is the unstable test core available on discord

**Comment by Arcade53** [comment]
can you give me the link so i can try it

**Comment by Kuba-J** [comment]
https://discord.com/channels/647909397477195803/807613978154762252/1039224684627116193

or  
[PSX_unstable_20221107_160557.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9961572/PSX_unstable_20221107_160557.zip)

**Comment by Arcade53** [comment]
got it.thanks where do i place the file

**Comment by Kuba-J** [comment]
console folder or do separate new folder :)

**Comment by Arcade53** [comment]
i have deleted the old rbf in console and put in this one

**Comment by Kuba-J** [comment]
ok but you didn't have to do it, there can be two :)
