### ISSUE TITLE
Silent Hill (NTSC-U):  Freeze to black screen after Sybil fight

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/PSX_MiSTer#149]
Issue:
Game hangs on a black screen (some audio keeps looping) after defeating Sybil, after the FMV.   Unable to progress.

Reproduce:
Load this save state, and wait for the FMV to finish playing (or press Start to skip it).  The game will the hang.

[Silent Hill_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8986849/Silent.Hill_1.zip)

Workaround:
N/A

BIOS:
SCPH-7501

CD Images:
Redump CHD

Core Version:
PSX_unstable_20220624_14eba5

**Comment by RobertPeip** [comment]
Game is already broken in the savestate. Do you have any slightly earlier savestate or memcard?

**Comment by Fuzzybane** [comment]
If you can send us a memory card save I will test it from there @AtomicShroom

**Comment by Fuzzybane** [comment]
also did you use any cheats or special options?

**Comment by AtomicShroom** [comment]
Here's my save file.  Load the "Theme Park" file. 

Note that upon retrying for what must be the 4th time, I was finally able to make it past the crash this time.  No idea what I did different, except perhaps that this time beat the fight on the first try without dying.  This might be it, might not.  I'll try and reproduce it further when I get some time.

How I reproduced it previously (and yes I did full reboots in-between):

1. Load the "Theme Park" save.
2. Get to the Carousel by walking in the opposite direction of the save pad, then to the right.  Visibility is low so you might have some trouble, but nothing can hurt you in this area so just run around until you find it.
3. Enter the Carousel, which will begin the Sybil boss fight.
4. Maybe die at least once and select Continue? 
5. Beat Sybil. (First you must run around her so that she will attempt to shoot at you with her gun and fail. You must do this until she uses all the bullets in her clip.  You'll know because you'll see a cutscene of her throwing away her gun when she's done. Then use the Hammer (already equipped) with R2 + X and swing at her until she dies. She takes a lot of hits. In the meantime she'll either grab you (causes very little damage) or slap you (cause much more damage), so watch your health and heal as necessary. 
6. Once you beat her, the FMV will play and you'll get the crash, maybe.

[Silent Hill.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8987295/Silent.Hill.zip)

**Comment by AtomicShroom** [comment]
> also did you use any cheats or special options?

No.

**Comment by Fuzzybane** [comment]
ok I will test your save and see if I can reproduce, did you try and complete the boss fight the other way as well by the way?

**Comment by AtomicShroom** [comment]
> ok I will test your save and see if I can reproduce, did you try and complete the boss fight the other way as well by the way?

No. This was my first time playing the game and it seems I missed that item during my playthrough. :/

**Comment by Fuzzybane** [comment]
ok so I followed your repro steps exactly, died a few times, selected continue every time and passed it first time I killed her, maybe it has something to do with the length of time you was playing the game or whatever was causing this bug was fixed between the build you was using and todays build, sorry but I could not repro this bug, also I was using bin/cue so could be an issue with CHD or the version of CHDMan you used to create the CHD.

**Comment by Fuzzybane** [comment]
Thank you for letting me test this though, it has made me wanna play it to completion again, I not played it since I was a child

**Comment by luke86** [comment]
I tried to reproduce the problem and could not. I loaded the game, died once, loaded it again and then won the fight. The game just went on until I could control the character again.

Notes:
Core version used: PSX unstable 22.06.26
Game version: USA release CHD format

**Comment by AtomicShroom** [comment]
I am no longer able to reproduce it either. Weird because when I originally got it, I got it at least 3 times in a row, and I rebooted my MiSter between attempts. But now I just can’t… no idea what happened. I mean the savestate I provided is proof something did go wrong. Must be something very random/timing-specific. Or maybe I undid whatever bug was set when creating new a new saves afterward? Who knows. 

Welp… I did some research and some people reported the same issue on a real PS1 with a real disc. Might be an actual bug in the game?

https://www.reddit.com/r/silenthill/comments/gkq26t/bugged_sh1/

**Comment by Fuzzybane** [comment]
hmm that is interesting

**Comment by Fuzzybane** [comment]
well if it is an actual bug can you close this issue?

**Comment by AtomicShroom** [comment]
Yeah all signs point to this being an actual bug with the game itself, not the core. Closing!
