### ISSUE TITLE
Time Bokan Series - Bokan GoGoGo (Japan) - Black box over Logo right after Bootscreen

### ISSUE THREAD

**Issue by luke86** [MiSTer-devel/PSX_MiSTer#150]
The logo right after the boot Screen has a big black box that covers a big chunk of the logo.

Screenshot of the problem:
https://imgur.com/a/58Wpwx7

Notes:
Core: PSX unstable 22.06.26
Game version: Japan
Format: CHD
vsync_adjust=0

**Comment by RobertPeip** [comment]
Cannot reproduce, works fine here. Please recheck with current version.

**Comment by luke86** [comment]
I made a mistake here because my rom folder on Windows sorts the games different from the mister.
The Problem exists in the game: Time Bokan Series - Bokan GoGoGo (Japan)

**Comment by luke86** [comment]
New Unstable build fixed the issue!
