### ISSUE TITLE
Tokimeki Memorial 2 (JP) - Game sometimes hangs while loading a scene or character

### ISSUE THREAD

**Issue by Mafu0567** [MiSTer-devel/PSX_MiSTer#152]
Issue: When playing the game normally, the game will sometimes stay stuck and not load the next scene or character. The game still responds if you press Triangle (which shows the date). 

BIOS: SCPH7000.BIN

CD Images: Redump CHD

Workaround: The scene will load correctly if the game is reset and loaded back from the last save.

Core version: PSX_unstable_20220627_15ed1e.rbf

[Tokimeki Memorial 2 (Japan) (Disc 2) (Rev 1)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9002786/Tokimeki.Memorial.2.Japan.Disc.2.Rev.1._1.zip)
[Tokimeki Memorial 2.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9002790/Tokimeki.Memorial.2.zip)

**Comment by Fuzzybane** [comment]
to me it sounds like a cd timing issue

**Comment by birdybro** [comment]
Can you test again with the latest release @Mafu0567 ? There were timing issues with the CD addressed recently.

**Comment by Mafu0567** [comment]
Sorry for the late reply, yeah I've been playing some more and there are still some infinite loads, though if it's CD timings it sounds like it's a known issue? This issue can be closed if so.

**Comment by RobertPeip** [comment]
i will take a look at the savestate the next days and try to reproduce

**Comment by RobertPeip** [comment]
Sorry cannot reproduce. How often does this happen? Does it happen after the scene where the savestate is from?

**Comment by Mafu0567** [comment]
I tested with the latest unstable build, on a normal playthrough save, no hanging on transitions between scenes, with default settings!
I'll close the issue.
Thanks for all the hard work!
