### ISSUE TITLE
Vagrant Story - End Game Credit Music 

### ISSUE THREAD

**Issue by Vampier** [MiSTer-devel/PSX_MiSTer#154]
**Reported by:** thoseposers

**Core**: PSX_20220618.rbf (latest release - _**notice: not unstable!**_)

**Description**: Audio during Vagrant Story credits has a loud warbly noise that drowns out any music you can hear. The loud noise lasts from beginning of the credits to the end. This save state should load into the middle of the credits

**Savestate**:[Vagrant_Story_USA_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9024646/Vagrant_Story_USA_1.zip)

Movie can be found at: https://discord.com/channels/647909397477195803/918220604736438272/992246277066731531

**Comment by RobertPeip** [comment]
fixed
