### ISSUE TITLE
Raiden DX graphical glitches with Rotate ON

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/PSX_MiSTer#155]
Only affects this part of the game, possibly because the menu is in interlaced mode. Low priority!

Rotate OFF

![IMG_20220701_102729](https://user-images.githubusercontent.com/7781739/176914414-8895ea7b-99dd-43fa-9e73-c1a5aebf5711.jpg)

Rotate ON

![IMG_20220701_102818](https://user-images.githubusercontent.com/7781739/176914365-2d9ddb85-c3db-4d8c-bd02-94f79f5ada13.jpg)

**Comment by RobertPeip** [comment]
480i cannot be rotated glitchfree due to the way it it drawn(Single Framebuffer in PSX VRAM).
This cannot be fixed unless the scaler itself would rotate, which is not planned as far as i know.

So we can either leave it as is or deactivate the rotate at all in 480i mode.
