### ISSUE TITLE
Virtual Memory Card using SNAC

### ISSUE THREAD

**Issue by nonochus** [MiSTer-devel/PSX_MiSTer#156]
I would like to suggest an improvement, if possible,  I have a snac similar to this:

https://github.com/blue212/SNAC-PSX

That it does not have a memory card port. What happens if you activate the snac on port 1 of the core and the snac does not have a memory card port? that the core looks for a real memory card in the snac and since it does not have a port, it is impossible to load/save the game.

Could the virtual memory card be implemented using the snac? once the snac is activated in the core, a virtual memory card for snac option should come out, if that option is turned off, that the core looks for the real memory card in the snac port and if it is turned on, a virtual memory card can be used, that way it would be possible for snacs users without memory card port to load/save game progress.

It can also be interesting to have the option even if you can use real memory cards in case you lack space on your physical memory cards.

Maybe there is some way to load/save game with the snac without a memory card port, I haven't been able to do it.

Regards and thank you very much, excellent work, the core works very well.

**Comment by RobertPeip** [comment]
SNAC and virtual/emulated memcard and pads all share the same data lines. Therefore you would need to know or guess proactive which device the game wants to connect to.

While this IS possible, I will not implement, as it's a lot of effort and can lead to many problems, including loss of data in situations where the guessing logic doesn't work correct or if the SNAC connected pad has any malfunction(e.g. broken cable).

What you can do:
- use a different port: Port 1 for SNAC, Port 2 for virtual Memory card, if the game can live with memcard in Slot 2.
- change the port at runtime from SNAC to emulated device to save, then change back
- use savestates to save
- build some adapter that allows to use a memory card
