### ISSUE TITLE
Gouketsuji Ichizoku 2 has a black screen

### ISSUE THREAD

**Issue by gdzjhgq** [MiSTer-devel/PSX_MiSTer#158]
Gouketsuji Ichizoku 2 has a black screen on the PSX core, using the Japanese version of the redump image Gouketsuji Ichizoku 2 - Chotto dake Saikyou Densetsu (Japan), black screen after the ATLUS logo is played. this game can run normally on the early beta PSX core

**Comment by RobertPeip** [comment]
duplicate with workaround: https://github.com/MiSTer-devel/PSX_MiSTer/issues/64
