### ISSUE TITLE
Resident Evil (USA)

### ISSUE THREAD

**Issue by odiaboeeu** [MiSTer-devel/PSX_MiSTer#159]
I'm playing Resident Evil 1 with Cris and the whole fmv during the game is loaded, stop and close and go back to the game. I am using redump without modifications and in CHD.

The first fmv with the capcom badge when loaded the game happens the same thing, start, load, break and skip the fmv.

I'm close to the final game and no bug happened, only all fmv are jumping during the game

**Comment by odiaboeeu** [comment]
https://youtu.be/M47BoMr4SMk

I recorded the fmv bug, there is no audio because I'm playing headset

**Comment by Kuba-J** [comment]
please check the game in bin/cue format and if you can attach the save file here

**Comment by SegaSnatcher** [comment]
Also, please provide save state before the FMV cutscene.

**Comment by odiaboeeu** [comment]
I tested the CUE version and the same problem happens. It follows Savestate at exactly the time before tyrant's FMV starts.

The savestate:
https://drive.google.com/file/d/1CMbH62ndcGTu-ZgRGrn9YaEFTNuMCFNC/view?usp=sharing

Remembering that every FMV happens the problem in the whole game, only opening and ending are normal. NOTE: It's the first version of Resident Evil to be released on PSX and it's not Director Cut

**Comment by Kuba-J** [comment]
vsync=0 ?

**Comment by odiaboeeu** [comment]
I'm using component video in a CRT, with IO Board and a single SDRAM

**Comment by odiaboeeu** [comment]
forget, by the way I don't know why the vsync was on 2, fuck I played the whole game without seeing an FMV. i'll close the problem
