### ISSUE TITLE
Dragon Ball Z Ultimate Battle 22 (Europe)

### ISSUE THREAD

**Issue by Brantyn** [MiSTer-devel/PSX_MiSTer#160]
**Issue**
Game palette is incorrect during the startup Bandai logo (appears green rather than red) and opening movie (greenish tinted). In-game palette after the opening movie looks fine.

**Reproduce**
Boot the game.

**BIOS**
7000

CD Image
Redump bin/cue

Core Version
PSX_20220702

**Comment by RobertPeip** [comment]
fixed
