### ISSUE TITLE
Tomba 2 save state crash

### ISSUE THREAD

**Issue by lsencabaugh** [MiSTer-devel/PSX_MiSTer#161]
About half way through Tomba 2 and today when I powered up the state loads in the correct area (Donglin Forest) but instantly the screen goes black, music continues, and game appears to softlock.

Attaching Save State File:

[Tomba! 2 - The Evil Swine Return (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9079993/Tomba.2.-.The.Evil.Swine.Return.USA._1.zip)

**Core Version / Build date**
PSX_20220702.rbf

**Comment by Kuba-J** [comment]
Are you using vsync 0 or 1/2? , Bin/cue or chd format?

**Comment by lsencabaugh** [comment]
It's in Bin/cue format. As for vsync I don't see that in my ini or the core settings, so I'm unsure but it would most likely be the default.

**Comment by bootsector** [comment]
Games are in the SD or external drive?

**Comment by lsencabaugh** [comment]
On SD Card

**Comment by Kuba-J** [comment]
> It's in Bin/cue format. As for vsync I don't see that in my ini or the core settings, so I'm unsure but it would most likely be the default.

Add in ini:

[psx]
vsync_adjust=0

**Comment by Fuzzybane** [comment]
do you have a memory card save near to where your savestate is? and can you pass the section by loading that? just curious as to wether it is related to the game or wether it is related to your state itself

**Comment by lsencabaugh** [comment]
@Fuzzybane I have a save file about an hour of gameplay back that stills works, as we as I'm able to proceed past that section. I had been using save states fine multiple times aside from this instance.

@Kuba-J I've added that line in but same results unfortunately.

**Comment by Fuzzybane** [comment]
maybe state corrupted?

**Comment by RobertPeip** [comment]
The savestate is most likely already corrupt. Why that is the case is hard to say. I can try to research it, but it's very unlikely.

Best is to have savestate that is still loadable in the area where it happens and then try to reproduce.

**Comment by lsencabaugh** [comment]
I tried to reproduce as I got to the same area in the game but it's working. It's probably not worth perusing so I'll just close this. Thanks for the responses!
