### ISSUE TITLE
physical memcards not working

### ISSUE THREAD

**Issue by cloudywu44** [MiSTer-devel/PSX_MiSTer#162]
the physical cards can not work on the PSX core 20220702 through SNAC ，but work well before the 20220618 PSX core.

my io board is 6.1
my physical cards‘ model  are japan scph 1020（ original cards）
my controller model is scph 1200
controller works well but cards not

**Comment by RobertPeip** [comment]
Not sure why you open this here again, the forum thread is already quite long...

Will link it here in any case: https://misterfpga.org/viewtopic.php?t=5023
