### ISSUE TITLE
Parasite Eve II PAL/NTSC

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#163]
**Issue:**
Characters shake when moving (Only during the scene with the skyscraper - MDEC related)

[PSX core PEII test](https://youtu.be/cXNDU-ptjvo) 

[PlayStation PEII test](https://youtube.com/shorts/Qx0zSUxAKxo?feature=share) 

**Reproduce:**

**Workaround:**
none

**BIOS:**
7001/7002

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DualSDRAM20220702

**Comment by castrodurl** [comment]
I test the game with the latest stable build (PSX_20220904) and apparently it's fixed.

**Comment by Kuba-J** [comment]
I checked just now in the PAL version, the last stable and unstable core, characters still shake when moving

**Comment by Kuba-J** [comment]
if the NTSC version works better , please send the video

**Comment by Kuba-J** [comment]
Fixed , test core 20221105
