### ISSUE TITLE
Suikoden (USA)

### ISSUE THREAD

**Issue by MarquisDeKazuma** [MiSTer-devel/PSX_MiSTer#164]
At the start of a large scale battle the game flickers rather than having a fade to white and then fade into the fight. 
This also occurs at the end of the fight with a fade to black. It does not occur in any other encounter other than the large scale ones.

[Suikoden Files.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9114346/Suikoden.Files.zip)

**Comment by ioev** [comment]
I just did one of these fights, and noticed that in the battle there is no background being rendered either.

**Comment by RobertPeip** [comment]
Fixed with newest testversion
