### ISSUE TITLE
Final Fantasy Tactics(USA)

### ISSUE THREAD

**Issue by MitchOgden** [MiSTer-devel/PSX_MiSTer#167]
MiSTer v220712
PlayStation 22.07.02

Game is freezing with an E3 error at the opening of the first scene at Orbonne Monastery.

Right after it shows Orbonne Monastery on the screen and it starts playing the music it freezes.

I have tried a fresh bin/cue with no luck in resolving the issue.

https://user-images.githubusercontent.com/53495900/179648475-15408256-c2d5-4f3a-a29e-a521101ed4c4.MOV

**Comment by birdybro** [comment]
This is a duplicate issue of --> https://github.com/MiSTer-devel/PSX_MiSTer/issues/32
