### ISSUE TITLE
Resident Evil 2 Italy - Memory Card doesn't save

### ISSUE THREAD

**Issue by aminta** [MiSTer-devel/PSX_MiSTer#171]
**Problem**
Resident Evil 2 (Italy) (Disc 1).chd

**Version**
PSX_20220702.rbf

It's impossible to use the memory card to save, it says "access error". Tried memory cards that work with other games with the core (Crash Bandicoot, Castlevania Symphony of The Night...) and also new raw .mcd cards on both slots.

**Workaround**
Use Save States

![IMG_7538](https://user-images.githubusercontent.com/1983688/181378695-f6957b67-51b0-42d6-98be-1e07a256ae52.jpeg)
![IMG_7539](https://user-images.githubusercontent.com/1983688/181378713-940388ec-9066-40a0-8bd4-b9e2d5fc1afa.jpeg)
![IMG_7540](https://user-images.githubusercontent.com/1983688/181378718-37e5ffd9-e2b4-4f71-bb43-ec597c5759e3.jpeg)
![IMG_7541](https://user-images.githubusercontent.com/1983688/181378722-c526d27b-bddb-41b2-933f-daf92b0c309a.jpeg)
![IMG_7542](https://user-images.githubusercontent.com/1983688/181378728-62a395d1-e276-4efc-9428-53c0a7bae053.jpeg)
![IMG_7543](https://user-images.githubusercontent.com/1983688/181378730-a4b3e2b3-b9a9-4bb1-a27a-a34ee672564f.jpeg)

**Comment by Kuba-J** [comment]
Works fine here 

https://youtu.be/mloKUDd56iE

**Comment by Kuba-J** [comment]
Do you have each game in a separate folder ?

**Comment by aminta** [comment]
> Do you have each game in a separate folder ?

No, this can be the problem?

**Comment by Kuba-J** [comment]
Yes, each game must be placed in a separate folder

**Comment by Kuba-J** [comment]
https://vampier.net/PSX/

**Comment by aminta** [comment]
OK, moved the two .chd files to "Resident Evil 2 (Italy)" folder, same error. I have the other games in the same USB drive and no problem with MC....

**Comment by Kuba-J** [comment]
Try running the game from the sd card

**Comment by Kuba-J** [comment]
And please try bin/cue

**Comment by Kuba-J** [comment]
One more question altogether important , are you using  cheats ? Do you have turbo , fast seek , or pal60 options enabled ?

**Comment by aminta** [comment]
> One more question altogether important , are you using cheats ? Do you have turbo , fast seek , or pal60 options enabled ?

Thanks! I had the turbo enabled: set it to "off" and now memory card works!
