### ISSUE TITLE
Pro-Pinball (USA) E3 Error

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/PSX_MiSTer#174]
So, this game works perfectly as far as I can tell, however, close to first booting up (when the game says "Loading..." in blue) an E3 will be thrown up, and remain as long as the game is running.  Everything seems to be fine, but the error persists.  This is a 480i game btw.  

The PAL version (Pro Pinball - The Web (Europe)) of the game does NOT throw up an E3, so maybe it's related to the resolution/frequency of the core.

**Comment by Hewhoisred** [comment]
PAL version gameplay is 704 x 506i
NTSC/USA version gameplay is 704 x 476i

**Comment by birdybro** [comment]
Confirmed this does still occur with the previous release, so this isn't a regression (just making sure since FFTactics would also give an E3 upon hang).

**Comment by Hewhoisred** [comment]
Sorry, I should have also mentioned this was mostly recently tested on the most current unstable build (PSX_unstable_20220730_1169fc), although the error also occurs in the main stable version of the core as well.

**Comment by RobertPeip** [comment]
False positive, new version will not show errors by default anymore.
