### ISSUE TITLE
Chaos Break (Japan)

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/PSX_MiSTer#175]
**Issue**
PSX Bios Logo Interlacing in background briefly

**Reproduce**
Boot game, at the start screen you will see it.

**Workaround**
none

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_DualSDRAM20220801.rbf

**Comment by mapfde** [comment]
Tried it with the SingleSDRAM version, and could reproduce the issue, but only on the digital output.

Checked multiple times, with both vsync_adjust=0 and 1.

BIOS: whatever update_all downloads
CD Image: Redump CHD
Core version: PSX_unstable_20220801_19f379.rbf

Display: Sony CRT on analog and DVI LCD 1600x1200

**Comment by RobertPeip** [comment]
I only see normal 480i<->240p switch garbage from scaler here. 

I don't think it's a game specific issue.

**Comment by wwark** [comment]
confirmed also on my side

**Comment by wwark** [comment]
Like discuss I closed this ticket.
