### ISSUE TITLE
Digimon Rumble Arena permanently hangs occasionally during gameplay [E2]

### ISSUE THREAD

**Issue by Lemonici** [MiSTer-devel/PSX_MiSTer#176]
I've occasionally gotten the game to hang during fights, but haven't played enough to find a pattern. I may leave it on the menu overnight to see if it'll happen anywhere. I've attached a savestate to right after it happened once but don't have anything to replicate it. 

Using BIOS 5501 if it matters.

[Digimon Rumble Arena (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9264291/Digimon.Rumble.Arena.USA._1.zip)

**Comment by Kuba-J** [comment]
Please retest , work fine here, no sign of E2, test core 20221105 , default settings, (no turbo, fast seek, cd speed hack etc )

**Comment by RobertPeip** [comment]
Kuba completed the game fully without issues. Will close it
