### ISSUE TITLE
Gamma option not working in psx core 

### ISSUE THREAD

**Issue by suww37** [MiSTer-devel/PSX_MiSTer#177]
I know that gamma can be set up in the menu option in another core. However, in psx core, it is impossible to set the gamma option and it is gray. The brightness is so bright on my sony monitor that I really need a gamma option, I wonder why the gamma option is not supported.

**Comment by birdybro** [comment]
The gamma option isn't currently supported as the video_mixer module was bypassed by Robert on purpose. I think Gamma as an option in the video_mixer module either uses DSPs (which the PSX core is using every single DSP possible on the FPGA) or stresses timing a lot (or both).
