### ISSUE TITLE
Firemen 2, The - Pete & Danny (Japan) - Sound and Music cuts out during a dialog scene in mission 2

### ISSUE THREAD

**Issue by luke86** [MiSTer-devel/PSX_MiSTer#178]
In Mission 2 of the Game very early there is a scene where the firemen find 2 People and have a chat. After a few seconds the sound and the music cut out and everything is silent until the scene is over. The next scene has sound again.

Workaround:
In the newest unstable Build there are 2 options that can prevent this problem from happening.
Setting the CD Speed to 1x or setting "Limit max CD speed" to ON. One of these 2 options is enough to make it work.

I also attached the following savestates:
State 1: End of Mission 1 they talk a bit and then Mission 2 is loaded
State 2: Beginning of Mission 2, there is 1 room to the right with fire and after this room the Scene with the dialog is triggered.
State 3: right before the Scene is triggered, just walk to the Right.

Savestates:
[Firemen 2 - Savestates.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9276560/Firemen.2.-.Savestates.zip)

Notes:
Core Version:
PSX_unstable_20220807_087a4c
PSX_20220727
Game version: Japan
Format: CHD
vsync_adjust=2

**Comment by luke86** [comment]
I retested the issue with the newest stable and then with the newest unstable and between these two versions something has changed. The dialog sound cuts off later in the newest unstable and once I even got it to play until the end of the dialog scene without cutting off.

I have reset my settings before testing to make sure nothing was changed from the standard settings. 

Hope this maybe helps with pinpointing what exactly is causing the bug. 

Tested Versions:
Stable: 22.09.25
Unstable: 22.10.05

**Comment by RobertPeip** [comment]
Thanks for retesting

As there are only some timing fixes that could be relevent in this new build, this suggests that the game depends on strict timing.

Hopefully the bug is gone once the timing work is "done".

**Comment by Kuba-J** [comment]
Fixed  , test core 20221106

**Comment by luke86** [comment]
Fixed for me too!
test core 20221106
