### ISSUE TITLE
Castrol Honda Superbike Racing (USA) - loading screen graphics missing

### ISSUE THREAD

**Issue by Vampier** [MiSTer-devel/PSX_MiSTer#179]
Core Version 08/06/2022 
Bios: USA (recommended version)
Workaround: not needed - just a minor glitch

To reproduce: start a race and watch the 'loading' screen. 

DuckStation is showing the same artifacts https://youtu.be/1kXXi0WehFw?t=108

The loading screen seems to do a video buffer flip when the game is loading. The results in the motor bike driver flickering on/off at a low frequency. 
![Screenshot from 2022-08-07 08-45-02](https://user-images.githubusercontent.com/12684428/183299242-e4e824ff-96d5-4daa-a474-b6d4c317865e.png)

**Comment by Vampier** [comment]
The graphics are now displayed during loading as expected. Thanks for the fix!

**Comment by Vampier** [comment]
Seems to happen again

**Comment by blisstik** [comment]
This is fixed with latest build.

**Comment by Vampier** [comment]
It's now fixed as @blisstik mentioned - thanks for the hard work!
