### ISSUE TITLE
Crash Bandicoot Collection 3 in 1 Bin/cue Buzzing Noise at Game Selection

### ISSUE THREAD

**Issue by cuentademierda1234567890** [MiSTer-devel/PSX_MiSTer#185]
**Issue:** Buzzing noise at the select game screen

**How to reproduce the bug:** Just boot up an image of Crash Bandicoot Collection which contains crash 1,2 and 3 at the same time after PS logo at the game select screen without choosing anything if you volume up you can hear the noise which is not present on original hardware neither when using a Ps2 . I'm not aware if there's issues with the games in general but fixing this noise should make the PS Core more accurate to the real thing

**WorkAround:** there isn't

**Bios Used:**

- 	SCPH-7001
-	SCPH-7000
-	SCPH-7002

**CD Image:** Image doesn't have any code only has a SYSTEM.CNF it's a ROM in internet which has a select menu in which you can select crash 1 2 or 3 which looks like this

![Untitled](https://user-images.githubusercontent.com/62609619/185765065-0a698ac0-892a-4a1e-9f2f-9a1e0827e1e5.png)

**Core Version:** PSX v220727

**Comment by Fuzzybane** [comment]
again please remove this link, romhacks are not bugs we accept

**Comment by RobertPeip** [comment]
Same as other bug
