### ISSUE TITLE
Next Tetris DLX (JP)

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/PSX_MiSTer#187]
Issue
Black Screen after intro

Reproduce
Boot the game, watch the logo's as they are unskippable, watch or skip the intro FMV

Workaround
Use Data Cache**

BIOS
7001

CD Image
Redump bin/cue

Core Version
2022 08 26

**Comment by wwark** [comment]
Another workaround is to have the two pads not set to "Off".

**Comment by RaspberryAlpine** [comment]
another workaround:
CD Speed: Hack 4X(U) or Hack 6X(U) or Hack 8X(U)

With those CD speeds the game makes it to the memory card check. This works with Pad2 set to Off as well.

**Comment by Vampier** [comment]
re-verified  with the November 9th 2022 build

**Comment by wwark** [comment]
Fixed !
