### ISSUE TITLE
Star Ocean - The Second Story (USA) (Disc 1) - E2 Error when buying/selling to a tools shop

### ISSUE THREAD

**Issue by eleriaqueen** [MiSTer-devel/PSX_MiSTer#189]
Game:
SCUS-94421 Star Ocean - The Second Story (USA) (Disc 1)

Hashes:
Star Ocean - The Second Story (USA) (Disc 1).bin
Crc: 473e2523
Md5: c560c795e534261f4a0df5c98099f905
Sha1: ccd092233b353d2aa7bb80ecdb2b76f456430b41

Issue:
E2 error when buying/selling some items to a tools shop.
Game doesn't seem to crash afterwards.

Core version:
220813

How to reproduce:
Go to a tools shop and either buy or sell 1 Spectacle.
It happens in multiple in-game towns but doesn't seem to trigger 100 % of the time.
(I've included two savestates, first one was done right before selling 1 Spectacle, the second one was taken after the error triggered)

[PSX.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/9484173/PSX.zip)

**Comment by RobertPeip** [comment]
E2 is just using a heuristic and might show up even without a problem. If there is no crash you can ignore the E2 code and turn off the error overlay (it's off by default)
