### ISSUE TITLE
DDR Mat SOCD filtering disabling

### ISSUE THREAD

**Issue by npcjuwow** [MiSTer-devel/PSX_MiSTer#190]
Hello! First of all, thanks for the great job! I'm having a blast with your core. Now, recently i got myself a DDR mat but i find out that i can't do opposite directions simultaneously since the core detects the mat as a joypad. This end up breaking the game since it requires these inputs at some points. Now, I don't know how hard it could be to fix this, but I just wanted you to know that this problem exist. Sorry, I'm just a noob that knows nothing about electronics or coding. I wish I could help with this instead of just raising a problem. At any rate, have a good one. o/

**Comment by RobertPeip** [comment]
The core/emulated joypad doesn't limit it, you can press up+down+left+right at the same time.
I played DDR with 2 different mats now and pressing both is very good possible with them.

I don't know why this happens for you :(

The only idea i have is that you maybe didn't map the buttons for the mat in mister main AND the core afterwards, so the default mapping could be on, which may prevent it?

**Comment by npcjuwow** [comment]
Oh, thanks for replying! Yeah, so I think it may just be my mat. I tested it on Windows 10 and it behave the same. Must be just some old firmware or who knows. Guess I will just have to go after a new mat. Anyway, thank you very much for your support! Have a good Sunday and a good week ahead of us!

**Comment by RobertPeip** [comment]
thanks for the response. If you still have any question, feel free to ask.

I will close the issue for now.
