### ISSUE TITLE
Fighters' Impact (NTSC-J)

### ISSUE THREAD

**Issue by mailcty** [MiSTer-devel/PSX_MiSTer#191]
Issue:
Sluggish performance in-game ([video](https://cdn.discordapp.com/attachments/918220604736438272/1016865321921036389/9-6-22.mp4). [reference from real hardware](https://www.youtube.com/watch?v=FCIDyao0eBs))

Reproduce:
Start the game and choose character(s) in either Arcade or Vs. Mode

Workaround:
Run the game in Turbo for improved performance, as demonstrated in the first linked video

BIOS:
SCPH-101

CD Images:
Redump CHD

Core Version:
PSX_20220904

**Comment by Kuba-J** [comment]
No change in core 20220916

**Comment by mailcty** [comment]
Seems to have been resolved as of version 20220926
