### ISSUE TITLE
Otona no Asobi (Japan)

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/PSX_MiSTer#192]
**Issue:**
Black screen after Playstation logo screen

**Reproduce:**
Start the game and you will have black screen after the Playstation logo screen

**Workaround:**
Active the turbo mode to go to the title screen

**BIOS:**
7000

**CD Image:**
Redump bin/cue

**More informations:**
DS commit for this game to fix it in 2020 but last version of DS have the same behavior as the Core.
https://github.com/stenzek/duckstation/commit/e5fc47a00836d6a4c873d8dbefb102f7765ee34a
Mednafen doesn't have problem to start the game.

**Core Version:**
PSX_DualSDRAM20220911.rbf

**Comment by RobertPeip** [comment]
broke from 8 24 to 8 26:
related to ram read timing slowed down from 5 to 7 cycles

**Comment by Kuba-J** [comment]
No change in core 20220916

**Comment by wwark** [comment]
Fixed with the version 20220919 !
