### ISSUE TITLE
Beyond the Beyond reboots core

### ISSUE THREAD

**Issue by cosmickatamari** [MiSTer-devel/PSX_MiSTer#193]
Attempt to start a new game of Beyond the Beyond. The core reboots. Attempted three times with the same results. Everything is up to date as of 9/12/22.

**Comment by birdybro** [comment]
When you select New Journey, press X instead of Circle :P

Circle is the cancel button so you are just backing out of that screen.

**Comment by Kuba-J** [comment]
yes, works very well, thank you for reminding me about this game :D
