### ISSUE TITLE
Tobal n°1 (EUR) (SCES-00497)

### ISSUE THREAD

**Issue by Grabou** [MiSTer-devel/PSX_MiSTer#197]
Minor bug.

**Issue**:
When you start the game Tobal n°1 in EUR version (SCES-00497) without activating the Fastboot mode, the PlayStation logo stays superimposed until the game is fully loaded.

**Reproduce**:
Start the game **with Fastboot mode Off**.

**Workaround**:
Launch game with Fastboot mode On.

**BIOS**:
Those downloaded by Update_All script and renamed boot.rom/boot1.rom/boot2.rom.

**CD image**:
Redump CHD

**Core version**:
PSX_20220925.rbf

**Comment by Kuba-J** [comment]
please close, it's already reported:

https://github.com/MiSTer-devel/PSX_MiSTer/issues/40

**Comment by Grabou** [comment]
Oh yes. :)
