### ISSUE TITLE
Dino Crysis 1 and 2 Won't Load.

### ISSUE THREAD

**Issue by jurkevicz** [MiSTer-devel/PSX_MiSTer#198]
With the Latest Release and Unstable Release I'm Unable to Load Dino Crysis 1 and 2.
I do have CD Fast Load on and CD Speed at 8X and Won't pass the Playstation Logo.

**Comment by RobertPeip** [comment]
Both work fine here with default CD settings.

Speed up settings are a hack and will not work with every game.
