### ISSUE TITLE
Sug: change default .mcd location to .../.../saves/PSX

### ISSUE THREAD

**Issue by edrozenberg** [MiSTer-devel/PSX_MiSTer#2]
A small idea to change default .mcd location to `/media/fat/saves/PSX`

Justification
- Users backing up or syncing their `saves` dir will also include their PSX memcards, will not forget to back up /media/fat/games/PSX
- Consistency with other cores which all save games in `saves`

I was able to manually navigate to that dir in PSX core prefs and I'm currently using:
```
/media/fat/saves/PSX/MemCard1.mcd
/media/fat/saves/PSX/MemCard2.mcd
```

Works great, no problems.

**Comment by sorgelig** [comment]
it's complicated because saves is unattended folder and not available for browsing.

**Comment by birdybro** [comment]
I'll add to the suggestion here how I personally think the automatically generated saves should work for this core when they are implemented. They should be by folder name, just as the other cores are often by filename.

The reasoning for this is that the internal game ID's are different for each disc, even for multi-disc games. And multi-disc games assume that the same memory card is used between each disc. There are other methods like mapping internal id's to game with some kind of database, but that could be complicated. Also, the first 40 or so launch titles did not have an internal ID, so most emulators have quirks for these games which might over-complicate the core if same thing were done.

I'm sure this was already planned, but just putting the idea out there ahead of time. :)

**Comment by edrozenberg** [comment]
@birdybro Thanks! I saw some of the discussion but will need to look into the details to really get how it works now.

**Comment by birdybro** [comment]
> @birdybro Thanks! I saw some of the discussion but will need to look into the details to really get how it works now.

I didn't do anything it was all @sorgelig thank him.
