### ISSUE TITLE
Castrol Honda Superbike Racing (USA)

### ISSUE THREAD

**Issue by Vampier** [MiSTer-devel/PSX_MiSTer#202]
After the intro logo and FMV 2 logos are supposed to show, Duck station shows the same behavior by displaying the same logos for about 1 frame.

Reference: https://www.youtube.com/watch?v=dPe-LH_lFM8

@1:33 it flashes the Interactive Entertainment logo
![image](https://user-images.githubusercontent.com/12684428/201410603-4038b4cc-3904-425f-9bc4-d32a55f39e1c.png)

@1:39 it flashes the Castrol Honda loading screen
![image](https://user-images.githubusercontent.com/12684428/201410537-eff0db7c-e985-4f88-8d56-16ee44a8a99b.png)

Kuba tested it on real hardware and confirmed the logos showed longer:
https://discord.com/channels/647909397477195803/918220604736438272/1040695576116863036 (link to conversation on Discord and extra reference information)

Tested with the November 9th 2022 core.

This ticket is for a different issue than the other Castrol Honda Ticket

**Comment by Kuba-J** [comment]
Fixed , test core 20221117 🙂

**Comment by Vampier** [comment]
Fix confirmed
