### ISSUE TITLE
Area 51 off-screen reloading is very spotty with GunCon3

### ISSUE THREAD

**Issue by phantomlord2oo** [MiSTer-devel/PSX_MiSTer#205]
The off-screen reloading is very difficult. Almost have to shoot a certain spot for it to work. Mechanic works perfectly in Maximum Force and Lethal Enforcers.

**Comment by misteraddons** [comment]
Can you verify with a GunCon2? Also, try other cores such as Genesis or SNES Lethal Enforcers. I'm not sure this is a core specific issue.

**Comment by phantomlord2oo** [comment]
I just tried with Lethal Enforcers on Genesis and SNES and the off screen reload works fine in the SNES (Genesis has a reload button for that). 

However, after more testing it seems like it's only the games that use the Justifier have this issue. All the GunCon specific games work fine.

**Comment by RobertPeip** [comment]
Justifier mode depends on timer/hblank tick counting, which is not tested against hardware yet and likely not correct.
Needs to be worked on.

**Comment by phantomlord2oo** [comment]
Ahh thanks for the head up on that!

**Comment by RobertPeip** [comment]
Fixed in newest unstable build
