### ISSUE TITLE
Ecsaform (Japan) (Disc 1)

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/PSX_MiSTer#206]
Issue:
Hangs in Image Works log screen.

Reproduce:
Launch the game and after some loops on attrac mode it hangs in Image Works logo screen. 

Workaround:
With Turbo (Low) it doesn't hang

BIOS:
7000

CD Image:
Redump bin/cue

Save state in attachment during the hang 
[Ecsaform (Japan) (Disc 1)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/10076964/Ecsaform.Japan.Disc.1._1.zip)

Core Version:
PSX_unstable_20221123_11f19b.rbf

**Comment by RobertPeip** [comment]
Seems more stable with Turbo Low. Unclear if the rest of the game works, as the issue only happens in a FMV that can be skipped.

DucksStation reports a bunch of problems this game runs into while playing the FMV:
[   52.5547] I/Bus: TTY: CD_init:addr=80052170
[   53.5907] I/Bus: TTY: CdRead: retry...
[   53.5913] W(ExecuteCommand): CDROM Pause command while seeking from 1215 to 62155 - jumping to seek target
[   61.8667] I/Bus: TTY: CD_init:addr=80052170
[   62.9027] I/Bus: TTY: CdRead: retry...
[   62.9032] W(ExecuteCommand): CDROM Pause command while seeking from 1215 to 62155 - jumping to seek target
