### ISSUE TITLE
Ridge Racer real hardware comparison seems to show some graphical inaccuracies

### ISSUE THREAD

**Issue by ghost** [MiSTer-devel/PSX_MiSTer#211]
Hi!

I use this wonderful core on a regular basis, but today I came across this tweet:
https://twitter.com/jamesfmackenzie/status/1599090577433165824

And then I checked this comparison video made by the same person:
https://www.youtube.com/watch?v=f6MuEhAtMiA

There seem to be some inaccuracies in how the car models are rendered:

1) The "jaggies" seem to be quite different in this angle:
![image](https://user-images.githubusercontent.com/119733144/205465504-c44232cc-816a-44d6-8119-3dcf4b29c803.png)

2) Here we can notice the yellow car has white line contours at distance on real hardware and not on the MiSTer:
![image](https://user-images.githubusercontent.com/119733144/205465576-4a014953-01a3-47cc-8a73-c32d95891b0e.png)

3) The lines around the windows and the bumper also seem to be drawn a bit differently:
![image](https://user-images.githubusercontent.com/119733144/205465676-3b082b50-3734-4ad8-b9f5-8d1c94654c8c.png)
![image](https://user-images.githubusercontent.com/119733144/205465687-35192b0c-5773-4443-955e-3cb38a05c1c8.png)
![image](https://user-images.githubusercontent.com/119733144/205465775-5f624488-0e8c-4516-971c-4ad123a95b74.png)
![image](https://user-images.githubusercontent.com/119733144/205465805-8ac9c15d-f116-43f9-81b1-e0f7b916e920.png)

**Comment by davedoc1984** [comment]
If I get chance, I will look at this compared to a few different Revisions of Real Hardware as I have a feeling this could relate to different GPU revisions (possibly?).

**Comment by RobertPeip** [comment]
How can you be even sure it's the 100% same content with so many moving parts?
It's from a video which is not using the original framerate(60hz vs 59.826 Hz), so it must interpolate between the frames.

It's totally possible there are differences, but with that noone can research it anyway.
Maybe try the same with a still image and integer upscaling only for both

**Comment by RobertPeip** [comment]
Closing this after discussion in discord about it and the user being deleted anyway
