### ISSUE TITLE
Aconcagua (NTSC-J)

### ISSUE THREAD

**Issue by mailcty** [MiSTer-devel/PSX_MiSTer#215]
Issue:
Sound buzzing when interacting with certain items on both Disc 1 & Disc 2

Reproduce:
[Disc 1 savestates](https://github.com/MiSTer-devel/PSX_MiSTer/files/10203110/Aconcagua.Japan.Disc.1._Savestates.zip) - On state 1, pick up book on the floor | On state 2, activate fire alarm and skip/allow cutscene to play
[Disc 2 savestate](https://github.com/MiSTer-devel/PSX_MiSTer/files/10203720/Aconcagua.Japan.Disc.2._Savestate.zip) - Open Julia's inventory and enable her lighter
[Aconcagua .sav file](https://github.com/MiSTer-devel/PSX_MiSTer/files/10203712/Aconcagua.Japan._Save.zip) - On Disc 1 save, activate fire alarm in Boiler Room (last door inside Communications Facility) | On Disc 2 save, progress through up to walking through the unlocked gate as Julia with her lighter on

Workaround:
Interact with the world enough to where the buzzing is gone?

BIOS:
SCPH-101

CD Images:
Redump bin/cues

Core Version:
PSX_unstable_20221209_168f57

**Comment by RobertPeip** [comment]
should be fixed with latest build, i confirmed with savegame from disc 1
Savestate will not be fixed, they are already broken

**Comment by mailcty** [comment]
Can confirm that both Disc 1 and 2 of the game have their sounds fixed; didn't realize there were also a bunch missing until now!
