### ISSUE TITLE
Castlevania Symphony of the Night (USA) - Freeze After Buying "Dracula" Tactic in the Library

### ISSUE THREAD

**Issue by ebenvenuti** [MiSTer-devel/PSX_MiSTer#217]
CHD image from Redump running in the most recent version available via update script as of 12/12/2022. Only special core feature enabled was 24-bit colors.

After buying the Dracula Tactics on the library the game runs Richter's initial segment automatically. After a while the game completely froze. I have it captured here (at roughly the correct timestamp already): https://youtu.be/2MMdn_Vgp4Y?t=3630

**Comment by Kuba-J** [comment]
please share savestate

**Comment by Kuba-J** [comment]
Yes, please share savestate in the library

**Comment by Kuba-J** [comment]
Check your chd file please , works fine for me bin/cue - no issues . I watched whole tactis tutorial with Dracula , works fine. I use default settings , tried with 24bit again without problems.

**Comment by Kuba-J** [comment]
Sorry i use unstable 20221209 , try this core please

**Comment by Kuba-J** [comment]
20221119 works fine too for me

**Comment by RobertPeip** [comment]
Works here, too. Using newest unstable + bin/cue

What is suspisious: for me and in the video of Kuba, the "now loading" screen is normal, while in your video it does spin around. I guess you use some mod?

**Comment by ebenvenuti** [comment]
I just tried a bin/cue with the same core build I was using before and it worked perfectly. Either the redump chd image is flawed or something got corrupted on my end. 

Thanks for the support... the idea was to report a bug to improve the core but the fault was on me in the end!

**Comment by RobertPeip** [comment]
No worries, this can happen. I'm glad the reason is found. Thanks for reporting back so fast!
