### ISSUE TITLE
N-GEN Racing - top 5% of the screen flickers during gameplay

### ISSUE THREAD

**Issue by thisisacleverusername** [MiSTer-devel/PSX_MiSTer#218]
top 5% of the screen flickers during gameplay and while in menus. 

Workaround:
Ignore it. It's distracting but not game breaking. 

BIOS:
NTSC, from update_all

CD Image:
removed

Core Version:
PSX_20221221

**Comment by Fuzzybane** [comment]
Good morning, thank you for this report but can you please remove this link, no piracy is allowed here and as a workaround can you please try using Fixed VBlank and setting the VCrop to the first set of numbers which is the NTSC Crop, Thanks In Advance

**Comment by Kuba-J** [comment]
It's not a bug in the core, it's the same with the original Playstation.  The area that flickers is not visible on crt TV, to get the same effect via hdmi in core use Fixed Vblank + Vertical Crop 224/270 + in-game option View + Screen Pos for correct screen positioning

**Comment by thisisacleverusername** [comment]
In fact, the menu is fully visible on the PS1 with official LCD screen, no flickering. No overscan cropping. 

That said, now that I look, it does appear that there is a VERY small line of flickering while in engine. It appears to be only the top 2 pixels. 

I guess this is a programming glitch in the game, though I'm pretty sure it's worse in the PSX core.

**Comment by Kuba-J** [comment]
again this is not visible on the crt tv whether it is with plasytation or psx core, the area visible on the LCD with Playstation or PSX core is the same!!!

**Comment by Kuba-J** [comment]
Psx core via lcd and crt

![IMG_20221224_202717](https://user-images.githubusercontent.com/95412885/209448943-7707d2ed-d6e6-4d37-88bb-1ecbbf2c595e.jpg)

Original Playstation via LCD

![IMG_20221224_201000](https://user-images.githubusercontent.com/95412885/209448953-56f5b906-6ba5-487b-8864-1535589cb8cf.jpg)

Looks the same , I don't know what parameters a dedicated lcd for the ps one has, these games were not produced for lcd but for crt

**Comment by thisisacleverusername** [comment]
Fair enough. Close it out.
