### ISSUE TITLE
Official Memory Card not working in bios and some games with the latest release

### ISSUE THREAD

**Issue by Personne72** [MiSTer-devel/PSX_MiSTer#220]
Its only affecting official ones. Third party memory cards works as expected.

Bios, Jumping Flash (1995), Crash Bandicoot (1996), Destruction Derby 2 (1996) : 

It seems like they detect something but its dropping communication for example Crash Bandicoot stays on "Reading memory card" all the time. The bios has those half a second freeze on the memory card menu acting like you keep plunging and unplugging a memory card.

Jet moto 2 (1997), Racing lagoon (1999), Need for Speed High Stakes (1999) :

Tested with those later games and they work perfectly.

 
Maybe early games communicate with the memory card differently idk
Tested with SNAC adapter + Multitap
Only the PSX_20221221 release behave like this. The earlier PSX_20221119 works as expected.

**Comment by blue212** [comment]
This is a known issue affecting builds after 11/28. It may only happen on certain versions of the sony MCs. maybe you could take a pic of the pcb of the cards that don't work for you. 
The one on the left seems to work and the right one does what you're describing. 
![MCs](https://user-images.githubusercontent.com/52429992/209886670-54e10c8f-22e4-40e0-9ea6-ccf1230230c8.jpg)

Here's a build that will fix it until I can find the cause.
[PSX_SNAC_revertSelect_20221204.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/10316980/PSX_SNAC_revertSelect_20221204.zip)

**Comment by Personne72** [comment]
These ones works fine :
![IMG_20221229_121957](https://user-images.githubusercontent.com/26470575/209945597-d9a9fbcc-1f7d-4f83-a309-5c6c9a58b59d.jpg)
These ones doesn't. however the gray one (SPC01K-001) seems to load a few save files in bios but drops communication after a second or two. The other two doesn't show anything : 
![IMG_20221229_121122](https://user-images.githubusercontent.com/26470575/209947138-2f7773c4-3a43-42fe-97dd-aeba5ee5cc79.jpg)
I hope this helps

**Comment by Kuba-J** [comment]
should be fixed, https://github.com/MiSTer-unstable-nightlies/PSX_MiSTer/releases/download/unstable-builds/PSX_unstable_20230109_050e2b.rbf

**Comment by Kuba-J** [comment]
> These ones works fine : ![IMG_20221229_121957](https://user-images.githubusercontent.com/26470575/209945597-d9a9fbcc-1f7d-4f83-a309-5c6c9a58b59d.jpg) These ones doesn't. however the gray one (SPC01K-001) seems to load a few save files in bios but drops communication after a second or two. The other two doesn't show anything : ![IMG_20221229_121122](https://user-images.githubusercontent.com/26470575/209947138-2f7773c4-3a43-42fe-97dd-aeba5ee5cc79.jpg) I hope this helps

Hi, have you had a chance to test the cards with the latest stable core yet? Everything should be working ok by now 🙂 ( Thanks blue! ).

**Comment by Personne72** [comment]
Yes it is indeed fixed thanks :)
