### ISSUE TITLE
Turbo Prop Racing (USA) graphical issues.

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#225]
Seems like the rendering pop in calculations (just a guess) is all messed up.

Video https://streamable.com/fvl6n4 It behaves the same with the 480p hack enabled.

Rapid Racer (Europe) which is the better version of the game doesn't have this issue.

I don't suppose there will be an option for "512i to 512p Hack" or at least combine the option of 512i/480i into one?
I'd prefer to play that version given the choice but not if it can't operate with a progressive hack. (Using LCD Monitor)

Rapid Racer (Europe) would look pretty good at 512p without it the game is a bit of combing eyesore and
the two deinterlacing techniques are not very favorable either.

**Comment by RobertPeip** [comment]
The 480p hack should work with 512i content as well.

No idea why the automatic detection doesn't work for this game. 
Maybe it's the same reason why the bugs appear in the NTSC version.

Can take a look later this week.

**Comment by HardwareBreaker** [comment]
> The 480p hack should work with 512i content as well.
> 
> No idea why the automatic detection doesn't work for this game. Maybe it's the same reason why the bugs appear in the NTSC version.
> 
> Can take a look later this week.

I did a quick check and the 512i issue seems to apply to these games too.

Ridge Racer Hi-Spec Demo (Europe)
Dynasty Warriors (Europe)

They also have a height of x512i too.

**Comment by RobertPeip** [comment]
with todays update:
- Turbo Prop Racing -> fixed rendering bug
- Turbo Prop Racing -> fixed both normal and 480p hack
- Rapid Racer -> fixed 480p hack
- Ridge Racer Hi-Spec Demo (Europe) -> fixed 480p hack

- Dynasty Warriors (Europe) -> 480p hack works ingame, but 2D menus are garbage with hack on, cannot fix that
- Atari Anniversary Edition Redux (Europe) -> pure 2D rendering, cannot do anything
- Motor Toon Grand Prix 2 (Europe) -> no idea how to unlock that mode, tried the cheat and it does nothing, you can try it
- All Star Boxing (Europe) -> gpu cannot hold 60fps with 480p hack, will not work with the hack
- Bloody Roar 2 - Bringer of the New Age (Europe) -> gpu cannot hold 60fps with 480p hack, will not work with the hack

**Comment by HardwareBreaker** [comment]
> * Motor Toon Grand Prix 2 (Europe) -> no idea how to unlock that mode, tried the cheat and it does nothing, you can try it

This video might help https://streamable.com/06j4g4

I'll try those games on the next update. 👍

**Comment by Kuba-J** [comment]
> > * Motor Toon Grand Prix 2 (Europe) -> no idea how to unlock that mode, tried the cheat and it does nothing, you can try it
> 
> This video might help https://streamable.com/06j4g4
> 
> I'll try those games on the next update. 👍

If you want you can check on test core with fixes
 [Test_core_20230118.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/10444689/Test_core_20230118.zip)
Or you can download it from Discord:
https://discord.com/channels/647909397477195803/807613978154762252/1065207870943141930
Greetings
