### ISSUE TITLE
Worms Pinball (Europe) video drop out.

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#226]
Worms Pinball video will drop out when you tilt the table with square. It loses sync on weave deinterlacing and goes black on bob

Video: https://streamable.com/6lwmfb

With regards to interlaced modes are there any thoughts or proposed solutions for games that are entirely 2D?
For example Worms Pinball looks pretty bad with Bob deinterlacing and of course Weave looks better until there
is motion which results in objects like the pinball and other small moving items becoming difficult to see.

**Comment by Toryalai1** [comment]
I cannot reproduce it. I tried the same settings as you and cannot lose sync. What vsync_adjust do you have set for the psx core? Do you have vrr enabled? Elaborate on what settings you have on the mister

**Comment by Kuba-J** [comment]
> > I cannot reproduce it. I tried the same settings as you and cannot lose sync. What vsync_adjust do you have set for the psx core? Do you have vrr enabled? Elaborate on what settings you have on the mister
> 
> I have it set to vsync_adjust=2 no freesync enabled. Although I don't think the image shouldn't lose sync from shaking the table regardless of sync setting.

"Fixed Hblank as well as Fixed Vblank can help delivering correct aspect rations and keeping the screen in sync with e.g. shaking animations. "

**Comment by HardwareBreaker** [comment]
The blanking options are off by default presumably because that is the most compatible setting? but you are suggesting they should be on by default?

**Comment by Kuba-J** [comment]
This is not an option from an Unsfae position, so it is safe to use, in order to eliminate such things. So it's all down to your preferences, I've been using these options since the very beginning when they appeared.

**Comment by Kuba-J** [comment]
Using some of the options also eliminates the artefacts in the right or top right of the screen that are normally invisible on a CRT, but then the screen is reduced in size because of the black bars, a choice I leave to you.

**Comment by HardwareBreaker** [comment]
Just for reference these pinball games also lose image sync when you tilt the table
Pro Pinball - Timeshock! (Europe) (En,Fr,De,Es,It)
Pro Pinball - Fantastic Journey (Europe) (En,Fr,De,Es)
Pro Pinball - Big Race USA (Europe) (En,Fr,De,Es)

This game does not
Pro Pinball - The Web (Europe).chd Does not lose sync when you tilt.

If I'm just retreading old problems then I'll stop.

**Comment by Kuba-J** [comment]
I assume that after using the fixed vblank option the problem does not occur in these games as well ?

**Comment by HardwareBreaker** [comment]
> I assume that after using the fixed vblank option the problem does not occur in these games as well ?

No I didn't test the VBlank option after Worms Pinball, I just changed the vsync_adjust to 1 which will result in a little more latency; the screen still goes black but the image doesn't lose sync.

The results of using fixed VBlank gives me a much smaller image than I'm used too. 
I'd rather not have that in all the games I play or have to turn it on for specific use cases. 
I'll just go with a solution that somewhat fits all games even if it is means the screen going black.

**Comment by Kuba-J** [comment]
Ok only I don't understand why you are still considering this in the context of an issue in the core , when it is precisely the use of fixed vblank that is supposed to prevent this. The problem is known , the solution for such games exists. I'm not going to explain it further because I don't think there's any point.

**Comment by HardwareBreaker** [comment]
I'm not sure I'm following what you are trying to say, You first indicate "you are still considering this in the context of an issue in the core" Then you say "The problem is known" followed by "the author of core did not decide to implement this solution permanently, precisely because of the reduced display area, he wanted to give a choice"

So it seems like you acknowledge that it is a problem with a compromised solution but you want to make some kind of further point? I already said I settled for a solution as previously mentioned. The solution for me is going to be different for someone else. I went for the one that comes closer to a real PS1 (avoiding changing options), which is to say avoiding an emulator like experience of switches and toggles to make stuff work.

I mean ultimately isn't that partly what the MiSTer FPGA experience is about? to offer a valid replacement/replica of the original hardware experience and not a just replacement for an emulator.

Anyway I'm not here to debate and only to offer reports.

**Comment by Kuba-J** [comment]
I have written that the solution to this problem is fixed vblank , what else don't you understand? If these cases were not known there would be no solution, and as you can see the solution exists.  Let's not debase ourselves with word games  , and neither do I intend to debate with you.

**Comment by birdybro** [comment]
Not to argue, but the original hardware experience didn't entail HDMI video output or having a scaler at all, and the PS1Digital certainly has some method similar to this to account for this behavior, as a result.

The fixed blanks options are there precisely because there are differences to account for with the conversion of the analog video to digital video.

**Comment by RobertPeip** [comment]
Fixed h/vblank is the accurate solution, but as you mentioned can lead to black bars, therefore it's not a default.

However, as long as you don't use vsync adjust 0, you will get sync drop without them on, because of the video timing being altered by the game to create the shake effect.

There is nothing the core can do: either give the game "room" to work with(black bars) or not support shake without sync loss.
