### ISSUE TITLE
Demo One (Version 1) (Europe) Graphics Garbage

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#227]
The Destruction Derby Demo on Demo One (Version 1) (Europe) shows graphical garbage on the right side of the screen.

The other demos seem fine.

Settings are default

Video: https://streamable.com/a9xvzl

**Comment by Kuba-J** [comment]
It's known  , use cropp option 

This also occurs in other games, I have already explained it

**Comment by Kuba-J** [comment]
https://github.com/MiSTer-devel/PSX_MiSTer#video-output

**Comment by Kuba-J** [comment]
It looks the same on real hardware , it has been verified many times, it is not visible on CRT
