### ISSUE TITLE
[Feature Request] Raphnet PS1/PS2 controller to USB adapter Support

### ISSUE THREAD

**Issue by osaeed18** [MiSTer-devel/PSX_MiSTer#228]
This adapter lets you use PS1 and PS2 controllers and multitap is also supported,
Has support for direct controller communication and Memory cards connected to a multitap can also be read and written to, 
https://www.raphnet-tech.com/products/psx_to_usb/index.php

Can this be added to the PSX Mister core to support memory card, vibration and multitap?

**Comment by RobertPeip** [comment]
For memcard it cannot work, as there is no path from the core to HPS for single memcard accesses, only block writes to save back where the core must be paused.

Not sure if multitap works out of the box with it behaving like a USB hub. If not, i doubt someone will write a special driver for the HPS side to support it.

Keep in mind that you can already connect your controllers, memcard and multitap directly through SNAC.
