### ISSUE TITLE
All Star Tennis '99 (Europe) (En,Fr,De,Es,It), Black screen

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#229]
Before a match begins the game gets stuck at a black screen

Default settings.

Video:  https://streamable.com/mmamds

**Comment by RobertPeip** [comment]
Some kind of race condition

workaround: set CD speed to 1x or 4x and it works...

**Comment by HardwareBreaker** [comment]
Animal Football (Europe) (En,Fr,De)

Seems to require the CD fastseek option too or you get a black screen after the language selection.

**Comment by RobertPeip** [comment]
Interesting, it loops around the same 4 sectors but never continues. Hopefully that game is easier to debug, but i doubt it's the same bug.

**Comment by RobertPeip** [comment]
All code monkey "games" and All Star Tennis 99 fixed with newest build
