### ISSUE TITLE
KKND Krossfire Demo (from Station Demo Disc 9) gets stuck on Please Wait after Mission FMV Plays

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/PSX_MiSTer#230]
**Issue**
After Mission FMV Sequence plays, the Demo gets stuck on the Please Wait Screen.

**Reproduce**
Start the Demo, let all FMV's play (Introduction and Mission) and you will be left on a Please Wait screen. On Real Hardware this does not happen. 

**Workaround**
none

**BIOS**
7502

**CD Image**
Redump bin/cue

Core Version
18/01/2023 Unstable Nightly Build

**Comment by davedoc1984** [comment]
Works in Duckstation.

**Comment by davedoc1984** [comment]
**Workaround** 
Use CD Speed of 8x to get this running.

**Comment by RobertPeip** [comment]
Or fastseek or CD speed4x/6x...another edge case CD timing

**Comment by HardwareBreaker** [comment]
This occurs with the full retail game too. KKND Krossfire (Europe)

**Comment by RobertPeip** [comment]
fixed with newest build, both demo and full game.
