### ISSUE TITLE
Lone Soldier (Europe) title screen garbage.

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#232]
There is extra graphical garbage on the right side of the title screen

Video: https://streamable.com/i5kewo

Horizontal Crop doesn't hide it. Title screen is interlaced.

Settings Default.

**Comment by RobertPeip** [comment]
This is normal behavior, it's just data in the framebuffer.
Might be hidden on a CRT, but not outside the defined resolution area, so crop will not crop it.

As it's not really a problem(no flicker, not really heavy garbage), i don't see why additional horizontal crop should be added for such a case.
