### ISSUE TITLE
Mille Miglia (Europe) (En,Fr,De,Es,It), Black Screen Loading Delays

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#233]
Mille Miglia (Europe) (En,Fr,De,Es,It)

Has about 20-30s loading delays with black screen. game still works though.

Video: https://streamable.com/ctbgs9

Default settings.

**Comment by RobertPeip** [comment]
I assume you have run it against original PSX to compare loading times? 

Some games have horrible loading times. E.g. "Lego Island 2" loads forever, but it's original behavior.

**Comment by HardwareBreaker** [comment]
> I assume you have run it against original PSX to compare loading times?
> 
> Some games have horrible loading times. E.g. "Lego Island 2" loads forever, but it's original behavior.

I ran it against Duckstation, The first alarm bell was the long delay before loading the first FMV after the trademark screen.
Which isn't normal.

**Comment by RobertPeip** [comment]
Only has about 8 seconds of black screen after PS screen with newest build. Either already fixed or something wrong on your side.

Verified via LBA overlay that all loading is without pauses or repeats until ingame. Yes, loading times are long, but nothing too crazy. DuckStation is no reference for loading times. So if you think it's wrong, you can reopen with PSX capture.
