### ISSUE TITLE
[Question] Analog output support

### ISSUE THREAD

**Issue by andrebrait** [MiSTer-devel/PSX_MiSTer#234]
Hi there.

Does this core support outputting all its video resolutions and sync signals, unmodified, through the analog output? 

i.e. is the core able to output all analog signals as a PlayStation would?

I'm likely going to hook up my Mister by using a SCART cable to my Retrotink 5X and the I'd prefer having the raw signal from the Mister go into the Retrotink rather than having the deinterlacer in the core use weave/bob (alongside the other timing/sync adjustments). 

If that's already supported, could it be made explicit in the documentation?

**Comment by RobertPeip** [comment]
Yes, output through analog out should be fine and conform to original timings.
It has been tested with several TV sets now, but i'm not sure how well it has been tested with Retrotink.
Feel free to report back.

As there are no issues known about it, i'm not sure which special note should be added to the readme. Analog out is already mentioned as working.

**Comment by birdybro** [comment]
Side notes:

1. Native 24-bit output over VGA on the Analog IO board is not currently possible, but there is a dithering option to get it to be just as good, so some 24-bit FMV will show some banding unless you enable this workaround in the video options for this core. This is a limitation of the analog IO hardware. The direct video adapter method does not have this limitation. It was not expected to be a problem when the hardware was designed originally.
2. The sync signal on the analog IO boards might be either slightly too weak or slightly too strong, so you will have to adjust the Retrotink's settings for gamma to offset this. There isn't an easy way around this, proper attenuated values would have required multiple larger components on the Analog IO board when there really isn't space for it. Here's the settings I had to use to line things up almost a year ago, the options in the firmware may have different names now:

![image](https://user-images.githubusercontent.com/16388068/214131301-ccb68741-e2c3-4936-be3d-96afb567a3b7.png)

Hope this helps.

**Comment by andrebrait** [comment]
It does help a lot. Thanks for this.

That's what could maybe be added on the Wiki or README regarding analog output.
