### ISSUE TITLE
Bishi Bashi Special (Europe) Black Screen.

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#237]
Black screen after first rolling demo on Hyper Bishi Bashi

Video: https://streamable.com/y0uo86

Default Settings.

PSX v230114

**Comment by Kuba-J** [comment]
Works fine with test core 20230120, so it's fixed.

**Comment by Kuba-J** [comment]
[PSX_unstable_20230120_160b86.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/10503280/PSX_unstable_20230120_160b86.zip) , here is core with fixes

**Comment by RobertPeip** [comment]
@HardwareBreaker: Why do you keep testing with old builds? not recheck old bugs that are fixed?
If you want to report further bugs, please do at least a little more homework:
- use the template that is used in most other Issues
- test with different versions to see if this is new or was always there
- test with different settings if any works as a workaround
- provide a savestate before the issue when it's deeper inside the game
- recheck your old bugs after a change was reported to fix them

Please don't expect me or others like Kuba to do all this work when you can also do it.

I usually wouldn't post that for someone who is just playing a game and finds a issue, but you seem motivated to try endless amount of games just to report them, which i define as "tester" and not as "user" and in this case it would be great if you could make the issue reports as high quality as you expect the core/fixes to be.
