### ISSUE TITLE
Love&Destroy (JAP) doesn't start

### ISSUE THREAD

**Issue by Louhike** [MiSTer-devel/PSX_MiSTer#238]
I've tried to play the NTSC Jap game Love&Destroy but it doesn't go past the boot sequence (with Sony and Playstation logos). After that, I only have a black screen. The error overlay doesn't display anything, the CD slow overlay neither. My game is a CHD redump.

**Comment by RobertPeip** [comment]
fixed in new testbuild (discord or unstable builds)
