### ISSUE TITLE
Silhouette Mirage is missing the music on the start menu.

### ISSUE THREAD

**Issue by Krathoon** [MiSTer-devel/PSX_MiSTer#241]
Silhouette Mirage is missing the music on the start menu.
It might be cd audio. I don't know for certain.

**Comment by Kuba-J** [comment]
Hi, Please check the image of your game, or setting. I can't reproduce it, music works fine. 

https://youtu.be/zh2h8n5iQq0

if you are reporting an issue , please provide:

The version of core you are using ?
Are you using the default settings in core ?
Image type bin/cue or chd ?
Version of the game JAP, USA  ?

Greetings

**Comment by Kuba-J** [comment]
The game is multi bin , you should have 26 bin files, separately for each audio track. If you only have one bin file that is the cause of the problems.

**Comment by RobertPeip** [comment]
There is also a testbuild for single bin images in the discord channel:
https://discord.com/channels/647909397477195803/737506076806611064/1065871098723455026

**Comment by RobertPeip** [comment]
Please reopen if there is still an issue
