### ISSUE TITLE
Feature Request: Toggle for Controller Rumble

### ISSUE THREAD

**Issue by FarawaySounds** [MiSTer-devel/PSX_MiSTer#242]
It would be a great addition to be able to disable rumble from the OSD menu. I like rumble in some games but other times I prefer to disable it when I can. I often do this with games on PC and PS3. Additionally rumble can be uncomfortable/annoying at times.

**Comment by Kuba-J** [comment]
As far as I know games that support vibration allow you to disable this option ?

**Comment by RobertPeip** [comment]
Please name some games where it's not possible to disable it. If you find some, i can add this option.

**Comment by birdybro** [comment]
https://github.com/libretro/libretro-database/blob/v1.9.0/metadat/rumble/Sony%20-%20PlayStation.dat - rumble support list from libretro if you'd like to test them out @FarawaySounds

**Comment by RobertPeip** [comment]
Will close this because no response. You can reopen in case you find games where it cannot be disabled
