### ISSUE TITLE
no Osd Dji 03 Air Unit

### ISSUE THREAD

**Issue by IKAFPV** [MiSTer-devel/PSX_MiSTer#243]
I don't have osd after i switch from vista to 03, I already did all what you can find on youtube or somewhere else but still don't have osd.
![331280016_1136652863692971_2574774141122787572_n](https://user-images.githubusercontent.com/125864932/220053641-0a7cc163-211c-4afb-b421-8ac943cd37aa.jpg)
![331401995_525511429693535_6357626642083490496_n](https://user-images.githubusercontent.com/125864932/220053649-b298469b-3d5f-44ee-854c-5d981456aba0.jpg)
![331539774_1181893145794379_6549683612725355254_n](https://user-images.githubusercontent.com/125864932/220053652-9163f54f-6481-4e81-93d7-5f339ab14b87.jpg)
![332237868_438639251756638_6263297804252163398_n](https://user-images.githubusercontent.com/125864932/220053654-6c6967d9-85f5-432d-8cfe-2534743679a3.jpg)

**Comment by Kuba-J** [comment]
Are you sure this is a good place to ask about  DJI 03 AIR UNIT ? :)

**Comment by IKAFPV** [comment]
> Are you sure this is a good place to ask about DJI 03 AIR UNIT ? :)
I think it is not about 03, I need to configure Betaflight somehow

**Comment by IKAFPV** [comment]
![20230219_154526](https://user-images.githubusercontent.com/125864932/220059399-8b569b2e-f35a-44f6-97cf-feb035e6597b.JPG)

**Comment by IKAFPV** [comment]
gray cable (SBUS) from vista was connected to rx4 on FC
![20230219_154526](https://user-images.githubusercontent.com/125864932/220059644-6fa8b5e8-4bb5-4291-93bb-d5ce974ec6ef.JPG)

**Comment by Kuba-J** [comment]
You are on the github page for PlayStation implementation in fpga. You won't find answers to your questions here :)

**Comment by IKAFPV** [comment]
> You are on the github page for PlayStation implementation in fpga. You won't find answers to your questions here :)

I was thinking it is betaflight :) Thanks
