### ISSUE TITLE
Koudelka (USA) FMV Jitters and tears

### ISSUE THREAD

**Issue by Shinmera** [MiSTer-devel/PSX_MiSTer#245]
It's pretty bad, so definite seizure warning about that. I recorded some video of it here:

https://youtu.be/xVF2l8X3fbA

Core: 2023.02.18

**Comment by Kuba-J** [comment]
Please provide more information, what region of the game, are you using default settings for the core ( no turbo, cd speed hack and others ) , are you using sd card or external media for games ?

**Comment by Shinmera** [comment]
As mentioned in the title, the USA region, all default settings, loaded off the microSD with no external media.

**Comment by Shinmera** [comment]
How odd, I'll try to verify the integrity of my copy then. Sorry for the noise if that was it!

**Comment by birdybro** [comment]
Side note: For safety, lots of old games can cause seizures, the PSX era is right around the last generation where they didn't seem to care about this and often didn't put in any warnings at all about it. If you are very prone to seizures, I would be very careful playing any retro games at all.

That aside, what is the display you are playing on and are there any settings in your MiSTer.ini that are different than normal?

**Comment by Kuba-J** [comment]
short video, sorry for record quality https://youtu.be/tDqrbXyZq2c

**Comment by RobertPeip** [comment]
If it wasn't on sd card i would assume it's storage being to slow.
You can verify with activating the CD overlay if the speed of the storage is ok.
Otherwise please verify if it's a good image.

**Comment by birdybro** [comment]
It was on the microSD card, so another possibility is a failing SD card or counterfeit one which can cause drastic reductions in read/write speeds.

**Comment by Shinmera** [comment]
Looks like I had a corrupted rom. Apologies for the noise!
