### ISSUE TITLE
Racingroovy VS hangs on Sammy logo

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/PSX_MiSTer#247]
The game Racingroovy VS works perfectly fine so there's no issue with the game running at all. The issue is that when the logo Sammy appears, the game hangs for about 1 minute before getting past it and to the menu.

I'm assuming this may be some kind of timing related issue.

**Comment by RobertPeip** [comment]
Game is waiting for memcard there.
Removing the virtual memcard(pressing back on memcard selection) or using SNAC without memcard will remove the waiting times.
Savestates can be used as workaround.

Still unclear if this happens on a real system or with SNAC and real memcard.

**Comment by RobertPeip** [comment]
Tested by blue1 and Splash in the MiSTerFPGA Discord:
- same time for virtual and real memory card(SNAC) on the core
- slightly faster loading with xStation on a real PSX, but same ballpark
-> no bug
