### ISSUE TITLE
PSX core does not support 15khz monitors

### ISSUE THREAD

**Issue by anderse77** [MiSTer-devel/PSX_MiSTer#248]
Core is cropped vertically on all 15khz tv:s. No modelines solve that. It is good to know for everyone trying to use this core.

**Comment by birdybro** [comment]
I haven't seen any cropping like you are describing compared to original hardware. For 15kHz you shouldn't need to use any special modelines, maybe you mean 31kHz?

How are you connecting your MiSTer to your CRT?

What game are you testing this with?

Can you please post your MiSTer.ini file so we can try and see if the problem is there?

**Comment by anderse77** [comment]
Via RGB scart and via analogue board v6.1. I am using vga to rgb scart adapter. The crt is 15khz, not 31khz. I am just testing with PSX menu. I have tried games like broken sword II wing commander IV crash and bandicoot and more.  I enclose my current ini file. If I set vga_scaler=0, no difference is seen. Still top is cropped of. I attach my mister.ini
[MiSTer.txt](https://github.com/MiSTer-devel/PSX_MiSTer/files/11174434/MiSTer.txt)

**Comment by birdybro** [comment]
Google around for "PS1 RGB SCART" and you'll see the cropping in PAL is normal on original hardware over SCART.

**Comment by anderse77** [comment]
Actually cropping is on ntsc in NES and SNES. No cropping on scart. Is there a way to deal with this cropping?

**Comment by anderse77** [comment]
I use this cable. I think that db9 is called rgb-scart. https://ultimatemister.com/product/mister-commodore-1084s/

**Comment by birdybro** [comment]
Ah, so you are using a commodore 1084s monitor? I can say that on regular consumer CRT TV's there isn't any difference between the PSX core and a real playstation. Do you have a way to connect a real playstation to your commodore 1084s CRT so you can compare output?

**Comment by Toryalai1** [comment]
The PSX core works with 15kHz monitors. This issue can be closed

**Comment by Kuba-J** [comment]
I know at least 30 people who use PSX core and 15kHz, and I also use such a solution myself. Title of this "issue" and the warning that it does not work with 15kHz can cause confusion.

**Comment by sorgelig** [comment]
CRT monitor even 15Khz is not the same as CRT TV. Monitor may have a special tweaks for specific video signals, so if it falsely recognizes such TV mode, it may switch to a special mode like overscan or special aspect ratio. So this issue may be related to a specific monitor only.

**Comment by RobertPeip** [comment]
The comment "on all 15khz tv:s" is wrong, it's more a problem of one user, who doesn't answer anymore when help was offered.

Feel free to reopen the issue if you think there is a bug, but for now noone else sees one that fits with the initial topic.
