### ISSUE TITLE
Thrasher Skate & Destroy USA - character selection screen broken

### ISSUE THREAD

**Issue by psychopat81** [MiSTer-devel/PSX_MiSTer#255]
Issue:
There is a bad glitch when entering the character selection screen, it happens 100% of the time. 
The main menu still appears behind and it's almost impossible to select anything. 
After around 30 seconds, the main menu behind disappear, however this issue doesn't happen with the original game on a real console. 

Reproduce:
From the main menu, select SKATE, the character select screen will load on top of the main menu. It's semi-transparents and everything is overlapped. 

Workaround:
After around 30 seconds, the main menu behind disappear, however this issue doesn't happen with the original game on a real console. Pressing the triangle, returns to the normal main menu, however the issue will happen again when pressing "Skate". 

BIOS:
SCPH-101

CD Images:
Redump bin/cues

Core version: fresh update as of July 1st, 2023. Unfortunately I have not noted the exact version. 

See reference image here
![IMG_0345](https://github.com/MiSTer-devel/PSX_MiSTer/assets/139100718/e0111666-4fc6-4e87-9cb0-67fe1073526b)

**Comment by Kuba-J** [comment]
I can't reproduce it. The game works fine. Are you sure you are using the default settings ? no turbo etc. ?

**Comment by Kuba-J** [comment]
Redump bin/cue , core 20230503, default settings
![IMG_20230710_205933](https://github.com/MiSTer-devel/PSX_MiSTer/assets/95412885/1965b0c9-6a5c-4f3d-9cf2-c03b271d53be)

**Comment by psychopat81** [comment]
> I can't reproduce it. The game works fine. Are you sure you are using the default settings ? no turbo etc. ?

Im pretty sure everything as at default yes, I will recheck again and note the core version and the settings and post an update. thanks

**Comment by psychopat81** [comment]
I had the convert to 480p option enabled, that is what caused the issue. Once disabled its working fine. Marking as resolved, thanks
