### ISSUE TITLE
Euro Demo 40 (Official PlayStation Magazine UK) F1 '98 Demo - Weird Menu Music Playing

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/PSX_MiSTer#256]
The Behaviour of the Core differs to Real Hardware when playing the F1 '98 Demo on Euro Demo 40.

On Real Hardware, the F1 '98 Menu plays no music at all which is correct behaviour for the Demo.

However, The Core plays some weird sounding music at the Menu (possibly getting it from another Demos Data?).

**Latest MiSTer Main Unstable
Latest Unstable Core Version
BIOS : Doesn't matter which version of the BIOS used.**

**Comment by Kuba-J** [comment]
For me there is silence in the menu, without strange music, tried single and dual core

https://youtu.be/zIrBpm9uQe0

Screen from the demo:

![IMG_20230728_111710](https://github.com/MiSTer-devel/PSX_MiSTer/assets/95412885/73f7ada8-70bf-4ee4-8c8a-2fb8bedc0fe3)

(If this is a different demo then I apologize)

Default settings , core 20230503 , bin/cue, bios 1002, ssd drive

**Comment by Kuba-J** [comment]
I also tried on the second Mister, sd card, bios 7502, all good
