### ISSUE TITLE
Euro Demo 53 - FIFA 2000 - After quitting the Demo by pressing Select, You get an E2 at the Powerline logo

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/PSX_MiSTer#257]
I appreciate this is very low priority and a minor issue the differs from real hardware.

Euro Demo 53 - FIFA 2000 Demo. If you press Select during gameplay to quit the Demo, when it goes back to the Powerline Logo, the Core throws up an E2 Error and hangs.

On my Real Hardware (SCPH-1000) it loads the Demo Menu back again with no problems.

Latest Stable MiSTer Main and PlayStation Core Used.
BIOS Doesn't matter which version I use.

**Comment by davedoc1984** [comment]
Tested this with my SCPH-5552 and it seems to behave the same as the Core. Possibly some Consoles are ok with it but others are not. Interesting....

**Comment by Kuba-J** [comment]
Tested with bios scph 1000 on core, works fine like on real hardware.

**Comment by RobertPeip** [comment]
It was discussed in discord, can we close it or is there still something open?

**Comment by davedoc1984** [comment]
Closing because the core does match Real Hardware.

When the SCPH-1000 BIOS is used with the Core, it behaves the same way as my Japanese SCPH-1000 Console.

When the SCPH-5552 BIOS is used with the Core, it behaves the same way as my European SCPH-5552 Console so it is accurate.
