### ISSUE TITLE
Graphical glitch in The Adventure of Little Ralph

### ISSUE THREAD

**Issue by InsertDiskTwo** [MiSTer-devel/PSX_MiSTer#26]
I have noticed that in The Adventure of Little Ralph (Chippoke Ralph no Daibouken) there are some graphical glitches that occur while scrolling - this is visible in the top few lines of the screen. Perhaps this can be looked into.

Thank you!

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/PSX_MiSTer#status - I don't believe Robert's ready to accept issues at the moment. The core is in a WiP state currently (but rapidly approaching a release condition personally).

**Comment by RobertPeip** [comment]
sorry, but we will open the bug section soon. For now bugs are tracked on discord.
