### ISSUE TITLE
Bishi Bashi Special (Europe & Japan)

### ISSUE THREAD

**Issue by glopgar** [MiSTer-devel/PSX_MiSTer#262]
In Europe version: 
Super Bishi Bashi works OK. 
Hyper Bishi Bashi does not respond to controller inputs.

Japanese version (there is only one game in it):
Does not respond to controller inputs

**Comment by Kuba-J** [comment]
Cannot reproduce 

Bishi Bashi Special EUR - tested with default settings , core 20230503 - Hyper Bishi Bashi - works fine , tested with DualShock 4

Bishi Bashi Special JAP - tested with default settings , core 20230503 -  works fine , tested with DualShock 4

**Comment by Kuba-J** [comment]
https://youtu.be/7hqh5PPrmZ8 - Bishi Bashi Special JAPAN

https://youtube.com/shorts/FE0kwE-EmmU - Bishi Bashi Special JAPAN

**Comment by glopgar** [comment]
OK I changed the buttons mapping and looks like some buttons work but other don't. The button I had assigned to START does not work so I couldn't start the game. Strangely, the main buttons assigned to square, triangle and circle don't work either.
This only happens in Hyper Bishi Bashi. In Super Bishi Bashi and other PS1 titles all buttons work OK.
