### ISSUE TITLE
King's Field (JP) English patch crashes when attempting to save at the first save point

### ISSUE THREAD

**Issue by cschmidt0121** [MiSTer-devel/PSX_MiSTer#266]
For some reason, attempting to save in the church at the beginning of the game causes the game to hang. The error overlay displays "E2" after the hang (screenshot attached).

This does _not_ occur on the original Japanese copy of the game, so this is an issue specifically with the English patch. That said, this patch runs on actual PSX hardware just fine... Not sure where that places this bug, but it really is a shame that this game isn't playable on the core. 

![20231031_221711-screen](https://github.com/MiSTer-devel/PSX_MiSTer/assets/4950661/6308e51b-697a-4efe-ac61-3729c16c9f27)

**Comment by RobertPeip** [comment]
Are you sure you tried the exact version on hardware?

Because there is a known issue and a fix available:
https://www.reddit.com/r/KingsField/comments/t8liso/cant_save_in_kings_field_jp/

**Comment by HungryGhostsFanTranslation** [comment]
Wow, I completely failed to find that fix. Admittedly it was a friend who played it on hardware which muddies up the bug report. Either way, I can confirm that fix makes the game playable on MiSTer. If nothing else hope this issue can be found by future people with the same problem.

Thanks!

**Comment by cschmidt0121** [comment]
Wow, I completely failed to find that fix. Admittedly it was a friend who played it on hardware which muddies up the bug report. Either way, I can confirm that fix makes the game playable on MiSTer. If nothing else hope this issue can be found by future people with the same problem.

Thanks!

**Comment by RobertPeip** [comment]
Thanks for reporting back!
