### ISSUE TITLE
spyro the dragon 2 and 3 PAL

### ISSUE THREAD

**Issue by Kaligulin** [MiSTer-devel/PSX_MiSTer#27]
Hello, after the sony screen, when the imsomniac logo appears E2 error, only PAL version, in the USA version it works fine.
Thanks for your great work.

**Comment by RobertPeip** [comment]
According to: https://github.com/stenzek/duckstation/wiki/Difficult-to-Emulate-Games
"Naive icache implementations will break - you need to handle partial line fetches from non-16-byte-aligned addresses"

This is not implemented in the core as the sdram memory controller is doing bursts of 16 bytes only. Doing partial fetches would exceed the timing requirements and is therefore not implemented or planned just for the copyprotection of this game.

**Comment by Kaligulin** [comment]
thanks for your clarification. great job, greetings.

**Comment by RobertPeip** [comment]
Will reopen this, so it's visible. Maybe there will be a solution some day.

**Comment by Fuzzybane** [comment]
**Workaround**
play USA versions for now

**Comment by RobertPeip** [comment]
fixed with latest commit

**Comment by Kaligulin** [comment]
Thank you very much for your excellent work.
