### ISSUE TITLE
NBA Hangtime - Graphical Glitch

### ISSUE THREAD

**Issue by buvk** [MiSTer-devel/PSX_MiSTer#272]
There is a horizontal line in the middle of the court.

![20240108_211028-screen](https://github.com/MiSTer-devel/PSX_MiSTer/assets/2666951/41e8e44a-bdb2-455f-a163-aa28b2cae139)

![20240108_211305-screen](https://github.com/MiSTer-devel/PSX_MiSTer/assets/2666951/ab5046ea-651d-4685-a618-d205eff00efb)

**Comment by Kuba-J** [comment]
Does this horizontal line occur in every match ? i do not see such a line.  Are you using the default settings ?

**Comment by Kuba-J** [comment]
https://www.youtube.com/watch?v=Ngd45989rW4

PSX core 20230503 , default settings ( no turbo , speed hacks, texture filters etc. ), bios scph 1001, media - micro sd card

I don't know how to reproduce your problem , write more details please. 

Greetings
Kuba

**Comment by buvk** [comment]
Hi.  Thanks for taking the time to check this on your end.  I just tested this again and I am not experiencing the issue today.  I assume opening another core prior to opening the PSX core must have caused this.
