### ISSUE TITLE
Wipeout XL graphical glitch: Screen blacks out when hit by a weapon.

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/PSX_MiSTer#276]
In Wipeout XL (USA), the screen will briefly black out every time your ship is hit by an enemy weapon (in first person view).  The screen doesn't black out on original hardware, and it makes the game difficult to play.

**Comment by Kuba-J** [comment]
Wipeout uses a shaking effect. You have to use vblank and hblank options.

**Comment by gleek12** [comment]
I'll try that.  Thanks!
