### ISSUE TITLE
Rollout crop information in the new MiSTer DirectVideo DV1 SPD Infoframe

### ISSUE THREAD

**Issue by lpuzzello** [MiSTer-devel/PSX_MiSTer#278]
MiSTer main and core template were updated in the last release (20240110) to provide the core resolution into the HDMI SPD Infoframe along with the Horizontal Decimation factor (how many times the DV horizontal resolution need to be divided) so any modern scaler like Retrotink 4K could automatically crop away the black bars and get the true content resolution (so it can draw scanlines at the correct scale, etc.)  

Unfortunately the crop information require each core to be updated manually to provide to the Main the size of the black borders.

Jotego cores were updated recently and are working perfectly.

SNES, Mega Drive and PCE have unstable releases, but are working fine.

I'm not a MiSTer Dev, but the following threads have some background and I'm more than happy to perform any test: 

https://github.com/MiSTer-devel/Main_MiSTer/issues/808

https://github.com/jotego/jtcores/issues/500

Although this is a scenario that doesn't affect many people (currently only those who own a Retrotink 4k). It would be great to have this functionality in the PSX core due to the mix of resolutions of this console.

**Comment by lpuzzello** [comment]
Hi, just giving an update. I tested the latest release (Mar-17th) and Auto-Cropping is working fine in RT4K. 
Tested with Chrono Cross and the scaler is framing the resolution when the menu is opened and closed. 
Tested with Tekken 3 and also is working.

Not sure if any other game with odd resolution changes can be tested, but for me is perfect fine and the issue can be closed.

**Comment by birdybro** [comment]
The updated release I just pushed a bit ago (20240318) will also resolve some issues that were observed in the 20240317 build that indicated problems on some DE10-Nano's and not others.
