### ISSUE TITLE
Dave Mirra Freestyle BMX (USA) hang and lockup

### ISSUE THREAD

**Issue by skankcore** [MiSTer-devel/PSX_MiSTer#282]
Repeated plays of this game reproduce a lockup after playing for a few minutes or simply letting the intro video play out. The game freezes and the audio loops a split second of the music.

**Comment by Kuba-J** [comment]
It's a known issue and already reported here.

https://github.com/MiSTer-devel/PSX_MiSTer/issues/169

**Comment by RobertPeip** [comment]
duplicate
