### ISSUE TITLE
Ridge Racer 1 Stutter

### ISSUE THREAD

**Issue by MrsBison** [MiSTer-devel/PSX_MiSTer#298]
Discovered this issue and its reproducible.

On Ridge Racer 1 every course.
At the very sharp right turn before the runnel where the helicopter is flying around.
Audio starts to stutter and the controlls are instantly ignored.

Means to keep up the pace you need to press gas button again.
Same on the construction side courses and on reverse.

Last post on the forum to this topic was 2022

**Comment by Kuba-J** [comment]
I can't reproduce it, I checked the US and EUR versions. The sound does not stutter and the controller responds well throughout the race. 

Core 20240418 , default settings.

Please share a video of where this is happening.

**Comment by MrsBison** [comment]
Hi Kuba. 
Thankx for fast reply. Ill check it later !! Maybe i also try other gamefiles.
Sometimes CHD are broken.

Laters

**Comment by Zet-sensei** [comment]
Just for more information.

I've tried the 3 main regions for the game (USA, Japan and Europe) in CHD format during the last hour.
CHD files were done by myself from personal dumps (same method as Redump) some months ago.

And I can't reproduce the issue too.

**Comment by MrsBison** [comment]
Ok i tried a new file. Bin Cue ...
Ridger Racer and RR Revolution runs absolutley flaweless....

So ticket can be closed. Thanx for the help.
