### ISSUE TITLE
Compiler looking for sys/pll_q18.qip file

### ISSUE THREAD

**Issue by Dysfunkshnl** [MiSTer-devel/PSX_MiSTer#3]
Quartus project processing fails, looking for a pll_q18.qip file in the sys folder.

**Comment by RobertPeip** [comment]
A you using Quartus 17 or 18 to build the project? You need to use 17, but it sounds like you are using18.

**Comment by birdybro** [comment]
@Dysfunkshnl Here's the correct versions of Quartus to use for almost any MiSTer core.

Windows - http://download.altera.com/akdlm/software/acdsinst/17.0std.2/602/ib_tar/Quartus-lite-17.0.2.602-windows.tar

Linux - https://download.altera.com/akdlm/software/acdsinst/17.0std.2/602/ib_tar/Quartus-lite-17.0.2.602-linux.tar

**Comment by Dysfunkshnl** [comment]
Reinstalled Quartus 17 to reset settings cache, and recompiled without
error. Thanks for following up with me.
