### ISSUE TITLE
Alien Resurrection USA

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/PSX_MiSTer#30]
**Issue:** 
Looping/corrupt sounds after starting new game

**Reproduce:** 
start new game after full BIOS boot(no fastboot)

**Workaround:** 
none

**BIOS** 
1001

**CD Image** 
redump bin/cue

**Core Version / Build date** 
PSX_DualSDRAM20220506.rbf

**Comment by RobertPeip** [comment]
**Reason:** 
Race condition leading to reading of SPU RAM at address 0x1A60 before writing it, making it use what BIOS had at this spot (0x0602) instead of the required value(0x0024)
SPU IRQ is used by the game, could be related

**Comment by Fuzzybane** [comment]
PAL Version reported working fine even with PAL60 mode enabled as a workaround and played at NTSC speeds

**Comment by RobertPeip** [comment]
- voice 23 is looping at spu address 0x200
- game writes voice 23 reg 2 -> samplerate 0x1000
- game writes voice 23 reg 3 -> ADPCM Start Address 0x0202
- game writes voice 23 reg 7 -> ADPCM Repeat Address 0x0202
-> because game is looping around in 0x200 but now gets 0x202 as repeat address, it jumps to 0x202 next time the adpcm loop is finished
- there was no data yet transfered there, so it runs up until 0x034c(x8 = 0x1A60) which contains 0x0602 from bios, causing the repeat address to be overwritten with 0x034c
- this happens 1.5 million cpu commands after setting repeat address
-> that leads to the game never reaching 0x202 anymore, but the irq trigger is set to that address

IF the voice would not run up at this point, what would happen instead is:
- 3.5 million cpu commands after setting repeat address: first data is transfered to SPURAM via DMA
- 4.2 million cpu commands after setting repeat address: RAM at 0x1A60 is overwritten
- 5.7 million cpu commands after setting repeat address: IRQ is enabled
- 5.9 million cpu commands after setting repeat address: Voice 23 is keyed on and set to 0x202

In duckstation it only works, because of a speedhack that makes voices that are off not calculate when IRQ is also off, so the repeat address is not overwritten
- if this speedhack is not used, it also shows this bug
- Using the speedhack in my emu and core fixed the issue
- even with this hack used, this does NOT solve the doorbug

mednafen and pcsx completly ignore loop adresses coming from new adpcm blocks when the voice was on for longer already and will keep the value written by CPU forever unless the voice is keyed on again

-> will use mednafens/pcsx behavior for now as it seems to most reasonable behavior

other possible solutions:
- SPURAM at 0x1A60 could be overwritten already by something else earlier
- there is could be some condition where the voice would not run up the address/update it's repeat address, no idea what that could be
- something could delay the DMA that will write to SPURAM and usually the values would be set earlier? 
Given the long time between (>100ms) that could only really be CD stuff, which is indeed still transferring data at that time, 
but even using 8x speed and instant seek doesn't make the DMA happen earlier
