### ISSUE TITLE
Pocket Fighter graphics glitch

### ISSUE THREAD

**Issue by xenyou** [MiSTer-devel/PSX_MiSTer#302]
Pocket Fighter (a.k.a Super Gem Fighter Mini Mix) has some glitch for graphics.
I'm using a redump image.

https://www.youtube.com/watch?v=s4yeNcThlIg

![Screenshot 2024-09-27 at 18 13 25](https://github.com/user-attachments/assets/5e058d32-75d6-4b0c-b09d-9384ebbe4e54)

![Screenshot 2024-09-27 at 18 13 45](https://github.com/user-attachments/assets/8b819915-aea3-447f-aa9f-573bdc683b75)

**Comment by Kuba-J** [comment]
are you using the default settings for the core ? ( no turbo , cd fast seek etc. ) , you are not using cheats ?

**Comment by xenyou** [comment]
OOPS, I was using x8 speed. Using original speed fix it.
Thanks!!
