### ISSUE TITLE
Graphical Glitch on Captain Commando (JP)

### ISSUE THREAD

**Issue by Primeira-Fase** [MiSTer-devel/PSX_MiSTer#303]
There is a graphical Glitch in the right side of the screen, only in HDMI signal, on CRT is normal. I am using CHD rom of the game.

**Comment by Kuba-J** [comment]
Fixed Hblank as well as Fixed Vblank can help delivering correct aspect rations and keeping the screen in sync with e.g. shaking animations. Both also offer crop options for games that depend on CRT viewports to hide artifacts at the edge of the image.

**Comment by Kuba-J** [comment]
it's not the core bug, please close the issue

**Comment by Primeira-Fase** [comment]
> it's not a core bug, please close the issue
> 
> use the HORIZONTAL CROP option in osd

Thanks.
