### ISSUE TITLE
Soccer '97 (PAL)

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/PSX_MiSTer#31]
**Issue:**
E2 after selecting the Team you want to play as and then pressing X.

**Reproduce:**
Reboot the Game / Reset the Core

**Workaround:**
Data Cache set to On allows the Game to continue.

**BIOS**
1001 or 5552

**CD Image**
redump bin/cue

**Core Version / Build date**
PSX_DualSDRAM20220508.rbf

**Comment by Fuzzybane** [comment]
this seems to have regressed further and now E2's at the spininng Eidos logo, Turbo still works as a workaround

**Comment by davedoc1984** [comment]
E2 at Eidos Logo no longer happening as of PSX_unstable_20220903_06b0b5.

However a new issue has surfaced, the text for some of the Menu screens is corrupted (See Select Language as an example).

Also the original E2 still remains after selecting the team you are going to Control. 

HOWEVER.... both the E2 at the Team Select Screen and the corrupted Text Issues don't appear to be a factor if you force the CD Speed to 6x and Limit Max CD Speed is set to ON. The game loads fine and plays fine so this can be used as a Workaround.

**Comment by Kuba-J** [comment]
Fixed, core 20221106

**Comment by davedoc1984** [comment]
Fixed. Thank you Robert.
