### ISSUE TITLE
Final Fantasy Tactics USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#32]
**Issue**
E3 error code shows before Orbonne Monastery scene after intro cinematic when you start a new game.

**Reproduce**
Start a new game, after naming your character and the first cutscen plays the game will hang

**Workaround**
Use Flynnsbit's Savestate linked below

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRam20220508

**Comment by birdybro** [comment]
Confirmed to still occur. Here is a savestate just moments before the hang for convenience.

[Final Fantasy Tactics (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8647235/Final.Fantasy.Tactics.USA._1.zip)

Build from 20220404 is the start of the regression. 20220403 does not reproduce the bug.

Here's the changes possibly related to the regression:
![image](https://user-images.githubusercontent.com/16388068/167303471-70e874cd-dd50-49f0-9f83-90c7b9e0b2dc.png)

The commit possibly associated:

https://github.com/MiSTer-devel/PSX_MiSTer/commit/fc17da111dce4d3166ecf028957f7815aed1d40e

**Comment by birdybro** [comment]
Another workaround. Turn on CD fast seek

**Comment by flynnsbit** [comment]
[Final Fantasy Tactics (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8683953/Final.Fantasy.Tactics.USA._1.zip)
Here is a savestate right after the bug for those that want to play.

**Comment by PenCapChew** [comment]
> [Final Fantasy Tactics (USA)_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8683953/Final.Fantasy.Tactics.USA._1.zip) Here is a savestate right after the bug for those that want to play.

I tried this savestate and it doesn't crash but the music is completely missing with only the occasional sound effect.

**Comment by castrodurl** [comment]
> Another workaround. Turn on CD fast seek.
> 
> Nvm, intermittent. It worked 3 times in a row then stopped working 3 more times in a row.

It works every time for me but, I have to switch System Type to PAL. 

I make a save state just before the scene and tried with different US and JP bios with and without CD fast seek and only PAL SCPH-1002 and CD fast seek Worked

**Comment by Fuzzybane** [comment]
Fixed now :) closing the issue

**Comment by JoshClose** [comment]
Do you know which update fixed this?

**Comment by Fuzzybane** [comment]
20220723 test-build/unstable nightly fixed it
