### ISSUE TITLE
Road Rash USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#35]
**Issue**
E2 randomly happens when listening to music in jukebox

**Reproduce**
Go into the options menu and pick the jukebox option, keep listening to the music in there and eventually will hang

**Workaround**
None

**BIOS**
7001

**CD Image**
Redump bin/cue

** Core Version**
PSX_DUALSDRAM20220508

**Comment by birdybro** [comment]
I think this is related to the Intro video loading if you are idle for some time no matter where in the menus. For me I was listening, heard it stop, looked to see if E2 occurred, but the intro video loaded instead. :)

This might be resolved. Not totally sure though.

**Comment by Fuzzybane** [comment]
This doesn't appear to be linked to a specific song, I can only trigger it by starting at the top of the list and by the time I get to Soundgarden - Rusty Nail is will hang with E2, I then reset and started at that song and went through to the end with no hangs, I really don't know what is causing this maybe it is not a bug at all? just don't use the jukebox in the menu and keep skipping songs...

**Comment by Fuzzybane** [comment]
Real Hardware Issue - Confirmed By Dave - Closing This
