### ISSUE TITLE
Ace Combat 3: Electrosphere (NTSC-U)

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#38]
**Issue:**
Game freezes on the "Now Loading" screen.

**Reproduce:**
Load the game and wait for the "Now Loading" screen

**Workaround:**
none

**BIOS:**
7001

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DUALSDRam20220508

**Comment by birdybro** [comment]
Confirmed and does not occur on latest DuckStation for reference.

**Comment by teknomedic** [comment]
Same issue on my setup with both Bin/Cue and CHD

**Comment by Fuzzybane** [comment]
Fixed with 06/10 test build
