### ISSUE TITLE
Option (or default behavior) request for attaching CD without reset

### ISSUE THREAD

**Issue by Paradox** [MiSTer-devel/PSX_MiSTer#4]
Right now, the core automatically resets, and loads the newly attached CD, this should not happen, one example of why is Grand Theft Auto Mission Pack #1 London 1969, it requires you to replace the CD with the original Grand Theft Auto CD in order to play, but, when you try to attach the GTA cd, it resets, and starts playing GTA... (Which actually hangs with an E2 error, after the loading screen, but, that's beside the point, right now...) I assume this also stops some multi CD games from working properly.

**Comment by sorgelig** [comment]
place both CDs into a single folder if you want to change them without reset.

**Comment by Paradox** [comment]
> 

That might be the fix for multi CD games, but, I'm not sure how, or if, that fixes the issue with GTA MP#1, but, I'll try it and see what happens.

**Comment by Paradox** [comment]
Nope, can't get it to work, even if I rename the cue files.

**Comment by Paradox** [comment]
doesn't even seem to work for multi CD games, I loaded the second disc of Oddworld - Abe's Exoddus, after pressing begin, it goes to the loading screen and asks you to insert disc 1, so, I press the menu button, choose the first disc, which is in the same folder, and, it just keeps telling me to insert disc 1.

**Comment by RobertPeip** [comment]
Disk swap is not implemented yet in the CD controller, it requires special handling (stop motor, open lid, ...) for the game to recognize the new CD.

**Comment by birdybro** [comment]
This seems to be implemented now, I was able to make it work, but you have to use the close and open lid option after selecting the second game.

Place all of the discs into the same folder for the game. Load the disc, get to the point in the game where you need to swap discs, load the 2nd disc, it shouldn't reset anymore. Then just toggle the close open disc lid option. Maybe this could be automated further at a later point, but just wanted to let @Paradox that it's mostly working :)

**Comment by Paradox** [comment]
@birdybro Yes, I have been using the unstable nightlies, and figured this out, as soon as it was added, but, thanks for replying.

**Comment by Paradox** [comment]
I just wanted to say that as soon as I saw this was implemented, more properly, recently, I opened GTA London, and tested, it works pretty flawlessly! Thanks @RobertPeip
