### ISSUE TITLE
Tobal 1 & Tobal 2 

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#40]
**Issue:**
Squaresoft Logo appears over the BIOS Screen

**Reproduce:**

**Workaround:**
fastboot on

**BIOS:**
7000/7001/7502

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DUALSDRam20220508

**Comment by birdybro** [comment]
Confirmed and this does not occur in Duckstation when tested just now with latest dev release.

**Comment by blisstik** [comment]
Toaplan Shooting Battle 1 (Japan) also has flickering on intro "Toaplan Legendary Series"

**Comment by blisstik** [comment]
Still exists PSX_DualSDRAM20221102.rbf

**Comment by blisstik** [comment]
This is now fixed

**Comment by Kuba-J** [comment]
Fixed , core 20221109
