### ISSUE TITLE
Primal Rage USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#42]
**Issue**
The CDDA Track for Chaos's stage doesn't play

**Reproduce**
Start a VS match against Chaos

**Workaround**
Use PAL version for now

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_2

**Comment by birdybro** [comment]
An easier way to reproduce this is go into options --> music test --> track 09. That track doesn't play on MiSTer, but it does play on Duckstation (albeit duckstation has the wrong offsets as the previous track's last second plays at the start of each next track).

**Comment by Fuzzybane** [comment]
PSX_DUALSDRAM20220508_3 fixed this so issue is closed
