### ISSUE TITLE
Dino Crisis 2 USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#43]
**Issue**
Every 2nd shot from a gun doesn't play the audio

**Reproduce**
Hold down the shoot buton and the audio from the 2nd shot won't play

**Workaround**
Only fire 1 shot at a time

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_2

**Comment by birdybro** [comment]
This doesn't happen in Duckstation, just tested.

**Comment by Fuzzybane** [comment]
fixed on 20220807 build
