### ISSUE TITLE
Ogre Battle - Limited Edition USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#44]
**Issue**
Audio cuts out during the initial dialog with Warren

**Reproduce**
Start a new game, this will happen in first 10 seconds

**Workaround**
Turn Limit Max CD Speed On 

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_2

**Comment by birdybro** [comment]
Side note: The bios sound effect persists and plays after the first company logo FMV by ATLUS and then the game title, but before the intro FMV, very subtle. Might be related.

https://user-images.githubusercontent.com/16388068/177009498-e4933676-d8be-4dfc-9425-af5c31edb846.mp4

**Comment by Vampier** [comment]
In game samples get cut off and battle music just stops as well - no real pattern to it as sometimes it just sounds fine. No urgency as the game still is perfectly playable.

**Comment by Kuba-J** [comment]
Music works with Limit Max CD Speed option enabled

**Comment by Kuba-J** [comment]
fixed, core 20221106

**Comment by Fuzzybane** [comment]
closing issue as it is fixed
