### ISSUE TITLE
Star Wars Episode 1 - The Phantom Menace USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#46]
**Issue**
Intro Text Crawl has an occassional blue shadow on it

**Reproduce**
Watch the intro and you will see it happen

**Workaround**
none

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_2
![20220429_112357-screen](https://user-images.githubusercontent.com/102825545/167304255-45bef141-f4f2-49fb-8d72-0c6291851de0.png)

**Comment by Vampier** [comment]
https://www.youtube.com/watch?v=5XwycNemnkQ

**Comment by birdybro** [comment]
This does not occur on Duckstation for reference. There are blue artifacts when the text is more scrolled up, but they are not as pronounced.

![image](https://user-images.githubusercontent.com/16388068/177009682-0c28fa42-eb55-4047-84e5-0c4c0b2e1e36.png)

**Comment by Fuzzybane** [comment]
this is getting better with every build, this only happened once today

**Comment by RobertPeip** [comment]
should be fixed with the newest version

**Comment by Fuzzybane** [comment]
> should be fixed with the newest version

will test in a few and then close it if it is fixed

**Comment by Kuba-J** [comment]
> should be fixed with the newest version

confirmed, works perfectly fine now :)

**Comment by Fuzzybane** [comment]
thanks for confirming Kuba, Closing the issue then
