### ISSUE TITLE
Tomba 2 USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#47]
**Issue**
Exploding Polygons on the fisherman at the start and in the background

**Reproduce**
Just start a new game

**Workaround**
none

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_2

**Comment by yavimaya** [comment]
Still same issue on the first public release of the core 20220511:

![20220512_100517-screen](https://user-images.githubusercontent.com/45275350/168047174-05ab1a4b-8ba0-44c2-b471-e6f9ca6fc64f.png)
![20220512_100538-screen](https://user-images.githubusercontent.com/45275350/168047122-ea6cf8ed-64f8-421f-9f61-cab21c8b1074.png)

**Comment by RobertPeip** [comment]
fixed
