### ISSUE TITLE
Dragonball Z Ultimate Battle 22 JAPAN

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#51]
**Issue**
Game stops loading at the first loading screen, issue is present on duckstation but not hardware

**Reproduce**
Just boot the game and after the Ban Dai logo the game will go to this loading screen

**Workaround**
Play the USA version

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by RobertPeip** [comment]
fixed
