### ISSUE TITLE
Transformers Beast Wars Transmetals USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#52]
**Issue**
Game will hang after the intro FMV

**Reproduce**
Boot the game, watch the first 2 logo videos, watch or skip the intro

**Workaround**
none

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by the-importer** [comment]
You'll get the same issue on a PSP by converting to a pspboot file or PS3 using an original disk. Try a lower BIOS version.

**Comment by Fuzzybane** [comment]
It won't help, I have tried it with 1001, 7001 and 101 the game has never got passed the intro on the core

**Comment by RobertPeip** [comment]
Info from mednafen:
October 31, 2018:
    PSX: Improved timing of CDC command 0x0A per tests on a PS1; fixes missing music and hangs in "Grind Session".

    PSX: Altered seek and pause timing and behavior per tests on a PS1; fixes hangs in "Incredible Crisis", "Ballerburg - Castle Chaos", "Transformers - Beast Wars Transmetals",
    and "Simple 1500 Series Vol. 057 - The Maze".

**Comment by RobertPeip** [comment]
After the intro, the game does send commands:
- Pause
- Pause
- SetLoc
- Seek
- Setloc
- Read
- Pause
After that it either stops forever and hang or will send GetStat and continue.

If the CPU speed is increased massive(e.g. 2X) from first Pause to second Setloc, the game will continue. But it's unclear why that is the case. The Pause time and the Seek time don't matter at all. They can be set to 10% of the original values and the game still boots fine with overclocked cpu.

Currently i have no idea how to further investigate.

**Comment by Fuzzybane** [comment]
Finally this can be closed. Fixed 20220801.
