### ISSUE TITLE
Evil Dead - Hail to the King USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#55]
**Issue**
Game loads as normal but when you get into game you can't actually leave your inventory to start playing

**Reproduce**
Start a new game, watch or skip the FMV's, Try and press Triangle to leave the inventory

**Workaround**
none

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by RobertPeip** [comment]
fixed
