### ISSUE TITLE
Next Tetris USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#63]
**Issue**
Black Screen after intro

**Reproduce**
Boot the game, watch the logo's as they are unskippable, watch or skip the intro FMV

**Workaround**
Use Data Cache**

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by RaspberryAlpine** [comment]
Another workaround: 
Set Pad2 to Off

**Comment by Vampier** [comment]
Verification if the bug still exists: Update 7/23/2022 - issue still exists

**Comment by RobertPeip** [comment]
Please retest with new testbuild

**Comment by RaspberryAlpine** [comment]
core version PSX_DualSDRAM20220826.rbf

Pad1 and Pad2 set to Dualshock

Turbo set to Off

The Next Tetris successfully boots to the title screen and the game is playable

**Comment by Vampier** [comment]
confirmed - works as expected

**Comment by Fuzzybane** [comment]
fixed 20220826
