### ISSUE TITLE
Gouketuji Ichizoku 2 JAPAN

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#64]
**Issue**
Black screen after Atlus logo

**Reproduce**
Boot the game

**Workaround**
When the Atlus logo is over, open OSD, reselect the Image and game will load

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by birdybro** [comment]
I don't think this happens anymore, I can't reproduce it.

**Comment by RobertPeip** [comment]
fixed
