### ISSUE TITLE
Die Hard Trilogy PAL

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#65]
**Issue**
The Die Hard Trilogy logo with the fire in the background shows for around 30 seconds

**Reproduce**
Boot the game, after the Fox and Probe FMV's this logo will appear

**Workaround**
Wait it out or play USA version

**BIOS**
7002

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by RobertPeip** [comment]
Game hangs because of accessing the memory card. You can remove the memory card to make it boot faster.

**Comment by RobertPeip** [comment]
Loading time is now ~10second with memory card and ~6 seconds without.

**Comment by RobertPeip** [comment]
It heavily depends on how many memcards and what is on the card.
- with no cards - 4 second
- 1 initialized card - 8 seconds
- 1 initiliazed card + 1 unformated - 10 seconds
- 2 initiliazed cards - 17-22 seconds, depending on the files on the card
- 1 initiliazed card + 1 empty - 28 seconds

Values from PSIO:
- with no cards - 2 second
- 1 initialized card - 8 seconds
- 2 initialized cards - 12 seconds
- 2 empty cards - 28 seconds

Overall, the situation using 2 non-empty cards might still be different on the core? hard to say, would need a real disk and 100% identic memory cards (e.g. SNAC) to test that.

**Comment by Kuba-J** [comment]
Real hardware PAL 7502 and 5502 + original game

- with no cards - 4 seconds
- 1 formated card - 9-10 seconds
- 2 formated cards - 15 seconds

**Comment by Kuba-J** [comment]
psx core + snac + memory cards , bios 7502

- with no cards - 4 seconds
- 1 formated card - 20-21 seconds
- 2 formated cards - 38 seconds

**Comment by Kuba-J** [comment]
Can snac affect the speed of reading from memory cards ?

**Comment by RobertPeip** [comment]
will close this based on agree with Kuba
