### ISSUE TITLE
Vigilante 8 USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#67]
**Issue**
red and black pixels on geometry in the distance

**Reproduce**
Load into a stage (Hoover Dam shows this well)

**Workaround**
none

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220805_3

**Comment by RobertPeip** [comment]
VRAM content(textures?) is broken after loading the stage. Works fine in the emulator and if savestate from emulator is loaded into the core.

Need to investigate further

**Comment by Fuzzybane** [comment]
appears to be fixed now so closing this issue 23/07/22

**Comment by JaydeSix** [comment]
> appears to be fixed now so closing this issue 23/07/22

Can you confirm it is still fixed on the most recent update?
It was fixed for me too on the previous test build but today's main release has the glitches again for me.
