### ISSUE TITLE
Gex 2 and 3 (USA) 

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#69]
**Issue:**
Level of detail issue, drawing distance is too short

**Reproduce:**
see atract mode, or play the game

**Workaround:**
none

**BIOS:**
7001

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DUALSDRAM20220508_3

![gex](https://user-images.githubusercontent.com/95412885/167407958-5d9e83e2-cbb0-4810-82de-c151f8c5b0b5.jpg)

**Comment by edrozenberg** [comment]
Might be worth retrying with the latest, just in case - [PSX_20220511.rbf](https://github.com/MiSTer-devel/PSX_MiSTer/blob/main/releases/PSX_20220511.rbf)

**Comment by RobertPeip** [comment]
fixed
