### ISSUE TITLE
X2 - No Relief PAL and JAPAN

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#72]
**Issue**
left most line is wrong

**Reproduce**
Boot the game, skip the FMV and either start a new game or wait for attract mode

**Workaround**
none

**BIOS**
7002

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by blisstik** [comment]
If there is a corrupted line on the left, this is the same as OG hardware.

**Comment by Fuzzybane** [comment]
> If there is a corrupted line on the left, this is the same as OG hardware.

I asked Dave to check it and he said it wasn't there on hardware so I kept it as a bug, send me a Discord DM of a pic of it looking normal on a HDTV on hardware and I will close this issue :)
