### ISSUE TITLE
Ian Livingstone’s Deathtrap Dungeon (NTSC-U)

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#75]
**Issue:**
No memory card found at save points 

**Reproduce:**
load and press square on the skull

**Workaround:**
none

**BIOS:**
7001

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DUALSDRAM20220508_3

**Savestate:**
[Ian_Livingstones_Deathtrap_Dungeon_USA_1.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8652016/Ian_Livingstones_Deathtrap_Dungeon_USA_1.zip)

**Comment by Fuzzybane** [comment]
Can confirm this as fixed
