### ISSUE TITLE
Breath of Fire 3 USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#77]
**Issue**
After first encounter with the boss on the mountain it stops accessing the memory card and game hangs

**Reproduce**
Play the game as normal until you have to go to the mountain, saving at the stone after meeting up with Rei will cause game to hang and all future save points will do the same

**Workaround**
Use Save States

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by bootsector** [comment]
Couldn't reproduce this issue. Saved in that stone just fine. Also, I was able to save just fine after defeating the chimera for the second time.

**Comment by Fuzzybane** [comment]
Closing this as it appears to be fixed :)
