### ISSUE TITLE
Dragonbeat - Legend of Pinball JAPAN

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#78]
**Issue**
Game hangs when selecting both auto and manual save UPDATE: Also without a memory card mounted

**Reproduce**
Boot the game

**Workaround**
None

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_20220511

**Comment by RobertPeip** [comment]
Related to interlace timing and status bits not matching expectations just as Next Tetris, Internal Section, and others

**Comment by Fuzzybane** [comment]
fixed and closing
