### ISSUE TITLE
FEDA 2 - White Surge the Platoon JAPAN

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#79]
**Issue**
Game hangs on a wait message if a memory card is inserted

**Reproduce**
Start the game with a memory card inserted

**Workaround**
Turn off auto-mount slot1 and unmount any memory card in slot 1 before loading the game then use save states

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220805_3

**Comment by RobertPeip** [comment]
Please retest with new testbuild

**Comment by Fuzzybane** [comment]
fixed 20220826
