### ISSUE TITLE
Games that Run Faster than Real Hardware

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#81]
Gouketuji Ichizoku 2 (NTSC-J) - seems fixed

Suiko Enbu (NTSC-J) - needs testing

Battle Arena Toshinden (NTSC-U) - seems fixed

**Comment by davedoc1984** [comment]
Toshinden's Gameplay is fine, its the Victory poses that are too fast.

**Comment by Fuzzybane** [comment]
All Fixed 20220826, closing this issue :)
