### ISSUE TITLE
[Feature request] overlay negating menu while cd is loading

### ISSUE THREAD

**Issue by asturur** [MiSTer-devel/PSX_MiSTer#84]
There is a behavior that blocked me  many times and that today @RobertPeip explained to me.
Pressing the menu button at the wrong time can tamper cd reads from the core.

It would be nice if we could use one of the error overlay in the top left corner to display a deny sign when the user press the menu button while the core needs data from the cd.
The menu won't open and the overlay would show up.

Not sure this is possible or worth, leaving it here so it can be discussed.

**Comment by RobertPeip** [comment]
New logic will pause the core when opening the OSD or HPS is busy, so issues should not happen anymore.
