### ISSUE TITLE
Flipped Screen Interleave mode issue

### ISSUE THREAD

**Issue by Vampier** [MiSTer-devel/PSX_MiSTer#86]
Tested on the 05/09/2022 core - this issue seems the pop up when the following conditions are met:

- Flipped screen 'on' in the Core GUI
- Interleave activated (hi-res screens)

I played around with the other video settings and nothing made a difference. 

I use sync=0 in MiSTer.ini - untested with other sync parameters.

https://www.youtube.com/watch?v=obGQBxShSJ0

**Comment by RobertPeip** [comment]
With interlaced drawing, there is only one framebuffer, so the drawing happens at the same time as the rendering, so it might not be finished when pulling the data if read out from the opposite direction. There is nothing i can do about that
