### ISSUE TITLE
Feature request:  Map Analog toggle to button

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/PSX_MiSTer#88]
Can the Analog toggle be made to be mapped to a controller button?  Would be more convenient.

I've got a spare button on my 8BitDo SN30 that would be perfect for this.

**Comment by sorgelig** [comment]
Do you mean switch between digital/analog mode of controller from button?

Btw, I have several 8bitDo controllers, and none of them have more buttons than PSX requires :)

**Comment by AtomicShroom** [comment]
Yes exactly that. The wired SN30 has two additional buttons (I guess “home” and “sharing?”). I have one mapped to the OSD and the other is unused, and could be used to toggle Analog/Digital: 

![7DE52553-F628-4ADE-A94F-0EB9B6139A82](https://user-images.githubusercontent.com/86253908/167974002-71ddb3de-a6ad-40d9-875c-f612159594cc.jpeg)

**Comment by Vampier** [comment]
Atomic: did you try to map that 'unused' button to something? Last time I tried I could not map it.

**Comment by AtomicShroom** [comment]
Aw heck, you’re right! It doesn’t do anything. :(

Nevermind then!

**Comment by Vampier** [comment]
no problem - it seems you can remap that button on the sn30pro2 though

**Comment by AtomicShroom** [comment]
Well I guess it could still be implemented as something mappable?  Maybe there exists a controller with a spare button that someone might want to map this to?  Or maybe there will exist in the future? Or maybe someone would want to map it to a keyboard key.  Why not just allow it?

**Comment by Vampier** [comment]
buttons can be mapped already

**Comment by Fuzzybane** [comment]
just use one of the button combo's that are selectable in OSD

**Comment by birdybro** [comment]
> I have a 8bitdo Pro 2 with a button in the middle of the controller that could be used as the Mode toggle. It'd be more convenient to have a dedicated button for Mode toggle than hitting the button combo (right now I use L1+L2+R1+R2+Dpad). And it'd be more like how the original PSX works. Obviously not a big deal but more of a convenience thing.

I don't think that button in the middle is mappable to xinput. It's just a profile switch button for the controller. The rear buttons aren't mappable either, they are just internal macros.

**Comment by spotanime** [comment]
> > I have a 8bitdo Pro 2 with a button in the middle of the controller that could be used as the Mode toggle. It'd be more convenient to have a dedicated button for Mode toggle than hitting the button combo (right now I use L1+L2+R1+R2+Dpad). And it'd be more like how the original PSX works. Obviously not a big deal but more of a convenience thing.
> 
> I don't think that button in the middle is mappable to xinput. It's just a profile switch button for the controller, you setup controller profiles with the 8bitdo ultimate software (cringe name). The rear buttons aren't mappable either, they are just internal macros.

Ah, that makes sense. For sure the rear buttons are that way, so likely you're right about that middle button.

In that case, it would be nice for the Mode select to cycle, so that for example hitting L1+L2+R1+R2+Dpad in ANY direction would cycle between Analog and Digital. That way, I could just map a macro to that middle button and cycle through Mode every time I pressed it, like how an original DualShock works.

**Comment by sorgelig** [comment]
adding such combo means removing it from possible button combos inside the game.

**Comment by missionfloyd** [comment]
PS4, PS5, and Switch controllers also have buttons to spare.

The PS5's mute button in particular seems perfect for the mode button. It can even light up, as can the Switch and 8bitdo home buttons, so the mode LED could possibly be implemented.

**Comment by birdybro** [comment]
> PS4, PS5, and Switch controllers also have buttons to spare.
> 
> The PS5's mute button in particular seems perfect for the mode button. It can even light up, as can the Switch and 8bitdo home buttons, so it might be possible to implement the mode LED as well.

The PS5 and PS4 controllers already have a default mapping. Press the touchpad as a button and it swaps modes.

**Comment by missionfloyd** [comment]
So _that's_ what the "DS Mode" option means by "Click".

**Comment by RobertPeip** [comment]
Implemented
