### ISSUE TITLE
Slam Dragon (jap)

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#89]
**Issue:**
Game runs very slow, in the menu and during battles

**Reproduce:**
Start the game and try to select a warrior

**Workaround:**
none

**BIOS:**
7000

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_20220511

**Comment by birdybro** [comment]
Tested in Duckstation and this doesn't occur, for reference. The FMV for the character selection in the first menu is supposed to be very low framerate (oddly enough), but you can select and change the fmv running.

Both duckstation and the psx core seem to end the jaleco screen too abruptly though.

**Comment by Kuba-J** [comment]
works perfectly fine :)
