### ISSUE TITLE
Wired DualSense Start Button Not Working

### ISSUE THREAD

**Issue by technomalogical** [MiSTer-devel/PSX_MiSTer#90]
I use a PlayStation DualSense controller wired via USB. In current release the right option button I have mapped doesn’t register a Start press in certain Konami games. Last worked for me in the 5/2 nightly build.

**Comment by Fuzzybane** [comment]
certain konami games like what?

**Comment by technomalogical** [comment]
Closing the issue. My Slot 1 controller was defaulting to Mouse instead of Dual Shock. This is apparently due to using a pre-release nightly and the order of the controllers being changed. Changing to Dual Shock and saving the changes resolved my issue.
