### ISSUE TITLE
King's Field graphics flicker

### ISSUE THREAD

**Issue by Rageypoo** [MiSTer-devel/PSX_MiSTer#91]
Hello, just wanted to let you know that King's Field (SLUS-00158) had 2 graphics issues I noticed when first trying it out, since it's not a well known game and more of a cult classic, it might have gone under the radar. 

When the game is "LOADING" a model of the main character comes out and shoots out a wave of energy, this character gets cut off in half at some point (not supposed to do that) 

Then as you play the game, sometimes the top portion of the game flickers. 

That's it, thank you!

**Comment by Vampier** [comment]
Please close ticket and add to https://github.com/MiSTer-devel/PSX_MiSTer/issues/34

**Comment by Kuba-J** [comment]
> Please close ticket and add to #34

King's Field in the US and EU is a completely different game.

**Comment by Rageypoo** [comment]
> > Please close ticket and add to #34
> 
> King's Field in the US and EU is a completely different game. The character referred to in the report only appears in King's Field EU/USA , this is King's Field II in JAP
> 
> https://en.wikipedia.org/wiki/King%27s_Field

Thank you I went ahead and included the SLUS for clarification!

**Comment by Vampier** [comment]
I stand corrected - seriously these things get too confusing :D

**Comment by Kuba-J** [comment]
> When the game is "LOADING" a model of the main character comes out and shoots out a wave of energy, this character gets cut off in half at some point (not supposed to do that)

When it comes to this moment, the same thing happens on the real hardware

![obraz](https://user-images.githubusercontent.com/95412885/168792652-fb1abe9e-c33e-4599-824c-e5ff1a3f86dc.png)

**Comment by davedoc1984** [comment]
Can confirm Kuba's comment above. Tested King's Field (USA) on my SCPH-1000 Japanese PS1 and this happens the same way (Character gets cut off).

**Comment by Rageypoo** [comment]
> Can confirm Kuba's comment above. Tested King's Field (USA) on my SCPH-1000 Japanese PS1 and this happens the same way (Character gets cut off).

well ty for checking it, I don't have the original game anymore...but I don't remember it cutting off like that, at all. guess it's faulty memory!

The top part of the screen flickering during gameplay is definitely not in the original though.

**Comment by Kuba-J** [comment]
> The top part of the screen flickering during gameplay is definitely not in the original though.

This happens with default settings ? Without data cache, widescreen etc?

**Comment by Rageypoo** [comment]
It should be default, I did a fresh MiSTer install and did update_all and it included the PSX core, I waited for the official PSX core release to do it. I don't know what data cache is and I haven't tried widescreen.

**Comment by Kuba-J** [comment]
> To be fair, the startup is also quite flickery as well, the SONY logo and then the PS logo when loading the CD I mean. It may not be the game itself, I could test other games. I haven't loaded many games on yet because you have to extract them first and I don't have high disk space on my SSD, sure would be great if we could keep them in .rar or .zip

This should not happen, the Sony and PlayStation logos are always ok, no flickering. I tested the KF and did not notice any flickering.

**Comment by Rageypoo** [comment]
thank you I will try this now. 
    On Wednesday, May 18, 2022, 12:32:45 PM EDT, davedoc1984 ***@***.***> wrote:  
 
 


Sony & PlayStation Screens Jumping up and down / Bobbing up and down? That is expected behaviour if your de-interlacing setting is set to Bob.

Set it to Weave and see if that helps.

**Comment by birdybro** [comment]
Yes, the startup flickering on the screen is known and would be very hard to fix. If anyone is curious about it, read here --> https://github.com/MiSTer-devel/PSX_MiSTer/issues/87#issuecomment-1124285560

**Comment by RobertPeip** [comment]
Is this resolved now or not?

**Comment by birdybro** [comment]
It can probably be closed, this isn't something that would be resolved in the Core, it would have to be changed in the Template most likely.

**Comment by birdybro** [comment]
Looks like it happens on original hardware according to @davedoc1984 so it's not a bug.

**Comment by Rageypoo** [comment]
I'll close it as assumed fixed for now, I wont have time to test the core again till this weekend, if I find it is still doing it i'll re-open it.
