### ISSUE TITLE
Tomba 2

### ISSUE THREAD

**Issue by badvision** [MiSTer-devel/PSX_MiSTer#93]
Tomba! 2 (The evil swine returns) has messed up geometry in character models pretty much right at the introduction, so it is very quick to reproduce without any real effort.

![20220513_174823](https://user-images.githubusercontent.com/5144198/168417454-b14d815f-edd2-4d5a-b283-45a20f9474f4.jpg)

**Comment by Fuzzybane** [comment]
this is a duplicate issue, already reported as issue #47

**Comment by badvision** [comment]
Sorry for the noise!  Thanks @Fuzzybane, @RobertPeip!
