### ISSUE TITLE
Cheats Not Working

### ISSUE THREAD

**Issue by RirseDeBlood** [MiSTer-devel/PSX_MiSTer#97]
Currently none of the downloaded cheats seem to do anything.

**Comment by birdybro** [comment]
First cheat I tested just now works fine.

https://user-images.githubusercontent.com/16388068/168525301-6ccd2b66-ed89-4fd7-aeac-92afe696de59.mp4

It's likely the cheats for the game you are playing just don't work correctly or they require another master code to work.

**Comment by RirseDeBlood** [comment]
Strange, I even tried Mega Man 8 before and none of the codes like mega jump and unlock all weapons were doing anything. Crash and Beyond the Beyond were also not showing signs of codes working for me.

**Comment by Jayde6** [comment]
do you have the data cache on? it disables cheats right?

**Comment by birdybro** [comment]
Yes, if Data Cache is on, cheats won't work. Maybe the option should be hard disabled upon enabling data cache in the future.

**Comment by RirseDeBlood** [comment]
That was the problem. Data cachce was there before cheats even had anything to use so I had it on. Turning it off and the first code I used work. Didn't seem to want to turn off when I switch that off but that is a minor issue that easily solved by saving and reloading. Marking as close.
