### ISSUE TITLE
Feature Request: Memory Card delay option

### ISSUE THREAD

**Issue by CharlesLove** [MiSTer-devel/PSX_MiSTer#99]
For games like CTR - Crash Team Racing, it is possible to swap out memory cards to load ghost data on the fly. The game only uses slot 1, slot 2 goes unused.

For example:
- Memory card A stores the player's overall progress.
- Memory card B stores the player's ghost data

Intended behavior:
1.  Load the game with the primary data memory card.
2. Go to time trials, you will see a star near crash cove indicating n trophy has been beaten on the primary data card.
3. Swap the memory card in slot 1 with a separate card that has ghost data for that course.
4. After a few seconds it will alert you that you have ghost data for that course. The star will still be present.

Current behavior:
1.  Load the game with the primary data memory card.
2. Go to time trials, you will see a star near crash cove indicating n trophy has been beaten on the primary data card.
3. Swap the memory card in slot 1 with a separate card that has ghost data for that course.
4. The time trial alert does not appear.
5. If you back out and attempt to load adventure mode, it alerts you that no memory card. Even if you swap back to the primary data card it will say there is no memory card present. (might be the best place to test hot swapping since it give the most immediate feedback)

I've attached a two memory cards below. The one named after the game has time trial progress, while the other one holds ghost data for crash cove.

[ctr hot swap test cards.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8701644/ctr.hot.swap.test.cards.zip)

**Comment by birdybro** [comment]
Does opening and closing the OSD in between any of these steps change the behavior?

**Comment by CharlesLove** [comment]
> 

Just tested. Same behavior. Can unmount a card just fine, remounting doesn't appear to register at all.

**Comment by birdybro** [comment]
It looks like when `reload memory card` was removed in the OSD it wasn't replaced by something to reload upon new mount. `bk_load` probably could have been instead just wired to something else that triggers upon mounting the memory card and retained.

**Comment by RobertPeip** [comment]
Using a game like Glover or SOTN will show you that mounting, unmounting and remounting without core reset works. The question is what the game needs to start recognizing the new card...

Just having no card connected for some time does not trigger a new card detection, so i have no clue.
